-- Seed data: 728 Tbilisi clinic leads imported from CSV
-- Generated automatically. All leads start as status='new', priority='medium'.

-- Batch 1: rows 1-50
INSERT INTO leads (name, category, district, address, phone, source, status, priority) VALUES
  ('Royal Dent', 'Dental', 'Vake', '39b Chavchavadze Ave.', '223 33 66, (596) 23 33 66', 'yell.ge', 'new', 'medium'),
  ('Dental Clinic Smile', 'Dental', 'Mukhiani', 'Mukhiani II M/D, B. 22', '(599) 38 04 78', 'yell.ge', 'new', 'medium'),
  ('Primero Clinic (Galaktion Makhviladze)', 'Dental', 'Saburtalo', '73 Tsintsadze St.', '(597) 26 87 87', 'yell.ge', 'new', 'medium'),
  ('Dental Room', 'Dental', 'Nadzaladevi', '18 Ts. Dadiani St.', '(597) 03 62 31', 'yell.ge', 'new', 'medium'),
  ('Eliz Dent', 'Dental', 'Saburtalo (Vedzisi)', '25 Gagarin St.', '214 45 45, (598) 94 45 45', 'yell.ge', 'new', 'medium'),
  ('Mikheil Tsereteli Dental Centre - Family', 'Dental', 'Temka', 'XI M/D, Q. 2', '(593) 95 05 06, (599) 00 11 58', 'yell.ge', 'new', 'medium'),
  ('Prima Dent', 'Dental', 'Saburtalo', '31a Kazbegi Ave.', '(599) 97 09 39', 'yell.ge', 'new', 'medium'),
  ('Unistom', 'Dental', 'Saburtalo', '3 Tsintsadze St.', '2 388 188, (571) 54 70 05', 'yell.ge', 'new', 'medium'),
  ('Dental Clinic DaVinci', 'Dental', 'Saburtalo', '166 O. Chiladze St., B. 10', '(595) 09 60 96', 'yell.ge', 'new', 'medium'),
  ('Maka Garibadze Dental Clinic', 'Dental', 'Varketili', 'Javakheti I Lane, B. 4a', '283 84 85, (593) 91 88 01', 'yell.ge', 'new', 'medium'),
  ('Vera Dent', 'Dental', 'Vera', '1 Kuchishvili St.', '222 54 52, (555) 22 54 52', 'yell.ge', 'new', 'medium'),
  ('Dentagram', 'Dental', 'Saburtalo', '18 Mitskevich St.', '237 00 81, (555) 37 00 81', 'yell.ge', 'new', 'medium'),
  ('Panorama', 'Dental', 'Gldani', '35 I. Vekua St.', '(596) 20 68 68', 'yell.ge', 'new', 'medium'),
  ('Dental Med', 'Dental', 'Saburtalo', '35 Kazbegi Ave.', '214 71 72, (599) 53 97 91', 'yell.ge', 'new', 'medium'),
  ('Smile', 'Dental', 'Didube', '12 Evdoshvili St.', '235 02 85', 'yell.ge', 'new', 'medium'),
  ('New Line Dental', 'Dental', 'Gldani', '55 I. Vekua St.', '(598) 37 40 36', 'yell.ge', 'new', 'medium'),
  ('Dental Clinic #1 TSMU', 'Dental', 'Saburtalo', '33 Vazha-Pshavela Ave.', '266 23 61, 295 32 09', 'yell.ge', 'new', 'medium'),
  ('Dental Clinic Crystal', 'Dental', 'Digomi', 'Digomi Massive, Q. 6, B. 18', '(597) 10 37 37', 'yell.ge', 'new', 'medium'),
  ('Nino Kordzadze Dental Clinic', 'Dental', 'Sanzona', '50 N. Shengelaia St.', '218 02 03, (568) 753 376', 'yell.ge', 'new', 'medium'),
  ('Urban Smile', 'Dental', 'Saburtalo', '3 Politkovskaya St., b. 14a', '(558) 00 10 20', 'yell.ge', 'new', 'medium'),
  ('Dental Clinic Kicha', 'Dental', 'Saburtalo', '39 Vazha-Pshavela Ave.', '(500) 05 05 39', 'yell.ge', 'new', 'medium'),
  ('Alba-Dent', 'Dental', 'Chugureti', '9 Z. Chavchavadze St.', '291 01 02, 230 96 01', 'yell.ge', 'new', 'medium'),
  ('32 Dent', 'Dental', 'Sanzona', '7a Guramishvili Ave.', '(579) 47 32 32', 'yell.ge', 'new', 'medium'),
  ('A Denta - Dental Care', 'Dental', 'Saburtalo', '45 Vazha-Pshavela Ave., b. 24', '(577) 72 92 52, 243 52 82', 'yell.ge', 'new', 'medium'),
  ('A1', 'Dental', 'Vake', '15 Paliashvili St.', '280 01 01, (599) 53 51 52', 'yell.ge', 'new', 'medium'),
  ('Aesthetics Dental', 'Dental', 'Didube', '113 Tsereteli Ave.', '(568) 34 87 27', 'yell.ge', 'new', 'medium'),
  ('Algan Dent', 'Dental', 'Didube', '19 V. Bagrationi St.', '235 32 33, (574) 42 42 38', 'yell.ge', 'new', 'medium'),
  ('Align', 'Dental', 'Saburtalo', '12 Ioseliani St.', '(550) 50 11 15', 'yell.ge', 'new', 'medium'),
  ('Amident', 'Dental', 'Ponichala', '32 Rustavi Highway', '240 14 53, (593) 10 29 62', 'yell.ge', 'new', 'medium'),
  ('Ana-Dent', 'Dental', 'Gldani', 'V M/D, B. 26a', '267 01 65, (599) 17 35 33', 'yell.ge', 'new', 'medium'),
  ('Anna Metreveli Dental Center', 'Dental', 'Saburtalo', '12 Aslanidi St.', '224 21 24', 'yell.ge', 'new', 'medium'),
  ('Antipos', 'Dental', 'Chugureti', '1 Kiev St.', '(599) 96 16 31', 'yell.ge', 'new', 'medium'),
  ('Apex Dent', 'Dental', 'Saburtalo (Nutsubidze)', '1 Ramaz Chkhikvadze St.', '229 51 97, (555) 320 027', 'yell.ge', 'new', 'medium'),
  ('Appledent', 'Dental', 'Vake', '118 Paliashvili St.', '222 56 17, (579) 22 56 17', 'yell.ge', 'new', 'medium'),
  ('Aqua Dent', 'Dental', 'Saburtalo', '29b Mitskevich St.', '(599) 05 14 14', 'yell.ge', 'new', 'medium'),
  ('Arkident', 'Dental', 'Didube', '1 Kereselidze St.', '234 27 17', 'yell.ge', 'new', 'medium'),
  ('BB Dent', 'Dental', 'Avchala', '18a Libani St.', '(599) 26 62 18', 'yell.ge', 'new', 'medium'),
  ('Beladent', 'Dental', 'Saburtalo', '72 Kostava St.', '(571) 21 22 57', 'yell.ge', 'new', 'medium'),
  ('Bema Dent', 'Dental', 'Samgori', '16 Zurab Iarajuli St.', '(571) 20 32 30', 'yell.ge', 'new', 'medium'),
  ('Bene-Dent', 'Dental', 'Sololaki', '48 L. Asatiani St.', '(577) 719 219', 'yell.ge', 'new', 'medium'),
  ('Beqa Dent', 'Dental', 'Varketili', 'Varketili 3, III M/D, B. 304', '(555) 43 38 95, (595) 970 970', 'yell.ge', 'new', 'medium'),
  ('Biomedi Dental Clinic', 'Dental', 'Digomi', '3 Mikeladze St.', '(557) 58 51 12', 'yell.ge', 'new', 'medium'),
  ('Blazy', 'Dental', 'Saburtalo', '2 A. Kalandadze St.', '(593) 140 150, 204 01 50', 'yell.ge', 'new', 'medium'),
  ('Bucho Dent', 'Dental', 'Varketili', '74/10 Kupradze St.', '(597) 01 03 17', 'yell.ge', 'new', 'medium'),
  ('Chiko Dent', 'Dental', 'Saburtalo', '76 Kavtaradze St.', '(591) 11 77 52', 'yell.ge', 'new', 'medium'),
  ('City Dent', 'Dental', 'Saburtalo', '68 Kostava St.', '299 77 45, (593) 12 52 84', 'yell.ge', 'new', 'medium'),
  ('Confidental', 'Dental', 'Avlabari', '78 St. Queen Ketevan Ave.', '(577) 000 167', 'yell.ge', 'new', 'medium'),
  ('CSI Clinic', 'Dental', 'Saburtalo', '46 Mitskevich St.', '(551) 04 72 75', 'yell.ge', 'new', 'medium'),
  ('Daily Dental', 'Dental', 'Vera', '3 Gudauri St.', '291 50 60, (595) 01 26 26', 'yell.ge', 'new', 'medium'),
  ('Davit Dent', 'Dental', 'Varketili', 'Kaloubani & Javakheti St.', '(593) 31 32 07', 'yell.ge', 'new', 'medium');

-- Batch 2: rows 51-100
INSERT INTO leads (name, category, district, address, phone, source, status, priority) VALUES
  ('Dekadent', 'Dental', 'Saburtalo', '74 Kostava St.', '218 02 24, (599) 97 09 24', 'yell.ge', 'new', 'medium'),
  ('Dent Adept (Saburtalo)', 'Dental', 'Saburtalo', '27g Mitskevich St.', '032 218 10 04', 'yell.ge', 'new', 'medium'),
  ('Dent Adept (Varketili)', 'Dental', 'Varketili', '10 D. Alexidze St.', '(596) 80 26 26', 'yell.ge', 'new', 'medium'),
  ('Ine Dent', 'Dental', 'Gldani', 'VIII M/D, B. 12', '(551) 18 30 96', 'yell.ge', 'new', 'medium'),
  ('Smile Solution (24-Hour)', 'Dental', 'Nadzaladevi', '105 Chkondideli St.', '(597) 91 99 90', 'yell.ge', 'new', 'medium'),
  ('Elite Dent', 'Dental', 'Mukhiani', 'II M/D, Building 5', '264 61 51, (598) 43 34 99', 'yell.ge', 'new', 'medium'),
  ('Dental Clinic (Avlabari)', 'Dental', 'Avlabari', '3v Kaspi St.', '274 64 46', 'yell.ge', 'new', 'medium'),
  ('Baiadenti', 'Dental', 'Chugureti', 'D. Uznadze St. 72', '95 46 65', 'kbilebi.com', 'new', 'medium'),
  ('Grinmedi', 'Dental', 'Sanzona', 'Likhvi St. 1a', '261 47 26', 'kbilebi.com', 'new', 'medium'),
  ('Global Dent Art', 'Dental', 'Saburtalo', 'Universitetis St. 2', NULL, 'kbilebi.com', 'new', 'medium'),
  ('Delta Denti', 'Dental', 'Sololaki', 'Dzm. Zubalashvilebi St. 27/9', '92 14 95', 'kbilebi.com', 'new', 'medium'),
  ('Denta Vita', 'Dental', 'Saburtalo', 'Vazha-Pshavela I Turn 1/43', '32 35 69', 'kbilebi.com', 'new', 'medium'),
  ('Dental Smile', 'Dental', 'Nadzaladevi', 'Ts. Dadiani 88', '2 30 90 92', 'kbilebi.com', 'new', 'medium'),
  ('Dental Office (Abashidze)', 'Dental', 'Vake', 'I. Abashidze St. 86', '22 08 79', 'kbilebi.com', 'new', 'medium'),
  ('Dental Luxi', 'Dental', 'Saburtalo', 'Bakhtrioni St. 13', '36 17 83', 'kbilebi.com', 'new', 'medium'),
  ('Dental Art', 'Dental', 'Saburtalo', 'Pekin St. 34', '38 04 97', 'kbilebi.com', 'new', 'medium'),
  ('Dentexi-95', 'Dental', 'Mtatsminda', 'Laghidze St. 13', '98 39 90', 'kbilebi.com', 'new', 'medium'),
  ('Dentixi', 'Dental', 'Gldani', 'Guramishvili Ave. 31', '47 63 31', 'kbilebi.com', 'new', 'medium'),
  ('Dent Line', 'Dental', 'Mukhiani', '3 M/R, Korp. 1', '63 55 28', 'kbilebi.com', 'new', 'medium'),
  ('Denta Luxi', 'Dental', 'Saburtalo', 'Vazha-Pshavela Ave. 12', '38 97 25', 'kbilebi.com', 'new', 'medium'),
  ('Dent Office (Dolidze)', 'Dental', 'Saburtalo', 'Dolidze St. 46', '2 90 77 90, 577 71 80 78', 'kbilebi.com', 'new', 'medium'),
  ('Denta Stili', 'Dental', 'Saburtalo', 'Bakhtrioni St. 20', '36 01 28', 'kbilebi.com', 'new', 'medium'),
  ('Dento-Luxi', 'Dental', 'Mtatsminda', 'Baratashvili St. 10', '(99) 19 66 23', 'kbilebi.com', 'new', 'medium'),
  ('Dentani', 'Dental', 'Saburtalo', 'Tashkenti St. 31', '38 00 67', 'kbilebi.com', 'new', 'medium'),
  ('Dentarti', 'Dental', 'Gldani', 'Metro Akhmeteli area', '635-935, 655-835', 'kbilebi.com', 'new', 'medium'),
  ('Dental-Eli', 'Dental', 'Didube', 'Stanislavski St. 12a', '35 00 81', 'kbilebi.com', 'new', 'medium'),
  ('Dentaprimi', 'Dental', 'Vake', 'Chavchavadze Ave. 33', '22 68 03', 'kbilebi.com', 'new', 'medium'),
  ('Dentist-Je', 'Dental', 'Chugureti', 'Marjanishvili St. 30', '95 68 73', 'kbilebi.com', 'new', 'medium'),
  ('Dentefekti', 'Dental', 'Isani', 'Agmashenebeli Ave. 128', '96 95 54, 96 47 94', 'kbilebi.com', 'new', 'medium'),
  ('Denti', 'Dental', 'Saburtalo', 'Vazha-Pshavela Ave. 78', '30 00 42', 'kbilebi.com', 'new', 'medium'),
  ('Dentiveri', 'Dental', 'Isani', 'Konstitucia St. 2', '95 42 68', 'kbilebi.com', 'new', 'medium'),
  ('Dental Georgia', 'Dental', 'Isani', 'Agmashenebeli St. 126', '95 75 60, 96 92 15', 'kbilebi.com', 'new', 'medium'),
  ('Dia Amo', 'Dental', 'Isani', 'Ketevan Tsamebuli Ave. 91', '56 83 77', 'kbilebi.com', 'new', 'medium'),
  ('Do-Manus', 'Dental', 'Saburtalo', 'Janashia St. 4', '29 09 74', 'kbilebi.com', 'new', 'medium'),
  ('DM', 'Dental', 'Saburtalo', 'Kazbegi 8', '38 22 08', 'kbilebi.com', 'new', 'medium'),
  ('Diadenti', 'Dental', 'Saburtalo', 'Nikoladze St. 7', '2 10 30 50, 2 18 01 01', 'kbilebi.com', 'new', 'medium'),
  ('Denta Klasi', 'Dental', 'Vake', 'Paliashvili Ave. 24', '230829', 'kbilebi.com', 'new', 'medium'),
  ('Dent Office Kei', 'Dental', 'Saburtalo', 'Mirotadze St. 1', '2 42 40 72, 568 18 27 27', 'kbilebi.com', 'new', 'medium'),
  ('Diakori-75', 'Dental', 'Digomi', 'Chachava N 1 / Lubliana N 1', '2 518 718', 'kbilebi.com', 'new', 'medium'),
  ('Evromedi', 'Dental', 'Nadzaladevi', 'Mtskheta St. 29', '25 09 06', 'kbilebi.com', 'new', 'medium'),
  ('Elendenti', 'Dental', 'Saburtalo', 'Shartava St. 44', '37 53 93', 'kbilebi.com', 'new', 'medium'),
  ('Eliti', 'Dental', 'Vake', 'Abashidze 47', '223051', 'kbilebi.com', 'new', 'medium'),
  ('Elit-Keramiko', 'Dental', 'Vake', 'Chavchavadze Ave. 37/14', '25 82 85', 'kbilebi.com', 'new', 'medium'),
  ('Embisi', 'Dental', 'Isani', 'Moskovi Ave. 5', '2702223, 593242179', 'kbilebi.com', 'new', 'medium'),
  ('Eskulapi', 'Dental', 'Saburtalo', 'Chiaureli St. 2', '54 04 54', 'kbilebi.com', 'new', 'medium'),
  ('Esteti', 'Dental', 'Chugureti', 'Tsinamdzghvrishvili St. 140/2', '296 84 88', 'kbilebi.com', 'new', 'medium'),
  ('Express-Denti', 'Dental', 'Varketili', 'Varketili 3rd Massive, Kv. 10', '73 19 93', 'kbilebi.com', 'new', 'medium'),
  ('Eshvi', 'Dental', 'Lilo', 'Lilo Settlement, Kv. 2, Korp. 2', '74 08 72', 'kbilebi.com', 'new', 'medium'),
  ('VPDental', 'Dental', 'Saburtalo', 'Kandelaki St.', '238 60 81', 'kbilebi.com', 'new', 'medium'),
  ('Varaziskhevi', 'Dental', 'Vake', 'Chavchavadze Ave. 2/2', '22 76 32, 22 27 95', 'kbilebi.com', 'new', 'medium');

-- Batch 3: rows 101-150
INSERT INTO leads (name, category, district, address, phone, source, status, priority) VALUES
  ('Varskvlavi +', 'Dental', 'Sanzona', 'Near Metro Ghrmghele', '(93) 68 45 55', 'kbilebi.com', 'new', 'medium'),
  ('Vivadenti', 'Dental', 'Didube', 'Tsereteli Ave. 73', '347284', 'kbilebi.com', 'new', 'medium'),
  ('Vistamedi', 'Dental', 'Vera', 'Shroshi St. 14', '18 33 18, 91 72 10', 'kbilebi.com', 'new', 'medium'),
  ('V. Margvelashvili Dental Clinic', 'Dental', 'Mtatsminda', 'Ingorokva St. 10', '98 57 72', 'kbilebi.com', 'new', 'medium'),
  ('Z. Margvelani Dental Clinic', 'Dental', 'Saburtalo', 'Mindeli St. 5', '(99) 11 00 03', 'kbilebi.com', 'new', 'medium'),
  ('Zetadenti', 'Dental', 'Gldani', 'Guramishvili St. 35a', '(032) 265 33 22', 'kbilebi.com', 'new', 'medium'),
  ('Zibexi', 'Dental', 'Saburtalo', 'Vazha-Pshavela 67/65', '323 103, 323 105', 'kbilebi.com', 'new', 'medium'),
  ('Zumadenti', 'Dental', 'Isani', 'Moskovi Ave. 42', '557 414182', 'kbilebi.com', 'new', 'medium'),
  ('T.F', 'Dental', 'Saburtalo (Nutsubidze)', 'Nutsubidze 3rd Mikr.', '555364767, 2147466', 'kbilebi.com', 'new', 'medium'),
  ('Imedi L-Denti', 'Dental', 'Vake', 'Kipshidze St. 7', '25 80 47', 'kbilebi.com', 'new', 'medium'),
  ('Irao', 'Dental', 'Didube', 'Kutaisi St. 31a', '34 30 63', 'kbilebi.com', 'new', 'medium'),
  ('Kuzanov-Denti', 'Dental', 'Saburtalo', 'Pekin St. 5', '42 40 05', 'kbilebi.com', 'new', 'medium'),
  ('Keramiko', 'Dental', 'Isani', 'Agmashenebeli 89/24', '95 10 99', 'kbilebi.com', 'new', 'medium'),
  ('Clinic 32', 'Dental', 'Vera', 'Nino Ramishvili 5', '597913026', 'kbilebi.com', 'new', 'medium'),
  ('Kristali', 'Dental', 'Saburtalo', 'Vazha-Pshavela Ave. 25a', '38 75 83', 'kbilebi.com', 'new', 'medium'),
  ('K&K (Kavsadze)', 'Dental', 'Vake', 'Kavsadze St. 10', '2 22 13 17', 'kbilebi.com', 'new', 'medium'),
  ('K&K (Javakheti)', 'Dental', 'Varketili', 'Javakheti St. 4', '2 73 69 09', 'kbilebi.com', 'new', 'medium'),
  ('Live Denti', 'Dental', 'Varketili', 'Kaloubani St. A/B Korpusi', '577 281 600', 'kbilebi.com', 'new', 'medium'),
  ('Lizadenti', 'Dental', 'Digomi', 'Robakidze St. 7', '52 00 36', 'kbilebi.com', 'new', 'medium'),
  ('Luka Denti', 'Dental', 'Nadzaladevi', 'Ts. Dadiani St. 134', '69 90 84', 'kbilebi.com', 'new', 'medium'),
  ('Minankari', 'Dental', 'Saburtalo', 'Gamrekeli St. 10', '384680', 'kbilebi.com', 'new', 'medium'),
  ('Miuler-Denti', 'Dental', 'Saburtalo', 'Vazha-Pshavela Ave. 6', '37 09 55', 'kbilebi.com', 'new', 'medium'),
  ('Mkurnali-93', 'Dental', 'Mtatsminda', 'Rustaveli Ave. 16', '93 33 69', 'kbilebi.com', 'new', 'medium'),
  ('Medi-Dent+', 'Dental', 'Vera', 'Arakishvili Lane #5', '91 49 35', 'kbilebi.com', 'new', 'medium'),
  ('Medidenti', 'Dental', 'Nadzaladevi', 'Ts. Dadiani St. 34', '66 33 35', 'kbilebi.com', 'new', 'medium'),
  ('Neo-Denti', 'Dental', 'Didube', 'Tsereteli Ave. 77', '34 74 88', 'kbilebi.com', 'new', 'medium'),
  ('Nero-Denti', 'Dental', 'Mtatsminda', 'Tsminda Nikoloz St. 2', '30 85 20', 'kbilebi.com', 'new', 'medium'),
  ('Niu-Denti', 'Dental', 'Saburtalo', 'Mitskevich St. 18 / Kazbegi Ave. 29a', '37 30 38, 36 22 94', 'kbilebi.com', 'new', 'medium'),
  ('Odontos', 'Dental', 'Saburtalo', 'V.Pshavela 3kv. Korp. 16', '2-32-04-25, 599 34 20 46', 'kbilebi.com', 'new', 'medium'),
  ('Paata Maghradze (24h)', 'Dental', 'Saburtalo', 'Pekin St. 43', '592119932', 'kbilebi.com', 'new', 'medium'),
  ('Pi Em Denti', 'Dental', 'Saburtalo', 'A. Politkovskaya St. 41', '592 444 952', 'kbilebi.com', 'new', 'medium'),
  ('Privat Denti', 'Dental', 'Saburtalo', 'Pekin St. 15', '+995 593 33 48 48', 'kbilebi.com', 'new', 'medium'),
  ('PS Dental', 'Dental', 'Saburtalo', 'Al. Kazbegi St. 37', '396098', 'kbilebi.com', 'new', 'medium'),
  ('Rea', 'Dental', 'Saburtalo', 'Kostava St. 76', '18 02 24', 'kbilebi.com', 'new', 'medium'),
  ('Royal-Denti', 'Dental', 'Vake', 'I. Chavchavadze Ave. 5', '22 61 68', 'kbilebi.com', 'new', 'medium'),
  ('SDASU Dental Center', 'Dental', 'Saburtalo', 'Tsageri St. 2', '37 53 97, 37 56 75', 'kbilebi.com', 'new', 'medium'),
  ('Sitidenti', 'Dental', 'Isani', 'Shevchenko St. 5', '98 84 12', 'kbilebi.com', 'new', 'medium'),
  ('Smile-Denti', 'Dental', 'Vake', 'Chavchavadze Ave. 11 / Kaloubani St. 14', '22 24 58, 76 75 91', 'kbilebi.com', 'new', 'medium'),
  ('Stimuli', 'Dental', 'Nadzaladevi', 'Mtskheta St. 8', NULL, 'kbilebi.com', 'new', 'medium'),
  ('Unidenti', 'Dental', 'Isani', 'D. Agmashenebeli 126', '94 03 94, 39 50 53', 'kbilebi.com', 'new', 'medium'),
  ('Ultradenti', 'Dental', 'Saburtalo', 'Bakhtrioni St. 11', '36 60 48', 'kbilebi.com', 'new', 'medium'),
  ('Feniksi', 'Dental', 'Didube', 'Tsereteli Ave. 117/2', '34 00 33', 'kbilebi.com', 'new', 'medium'),
  ('Shaini', 'Dental', 'Saburtalo', 'Gia Abesadze St. 3', '(93) 25 13 19', 'kbilebi.com', 'new', 'medium'),
  ('Chikodenti', 'Dental', 'Mtatsminda', 'Tavisuplebis Moedani 4a', '98 64 83', 'kbilebi.com', 'new', 'medium'),
  ('Tsedexi', 'Dental', 'Vake', 'I. Abashidze St. 56', '91 34 25', 'kbilebi.com', 'new', 'medium'),
  ('Tsito Denti', 'Dental', 'Vera', 'Arakishvili St. 2', '94-57-71, 94-57-72', 'kbilebi.com', 'new', 'medium'),
  ('Dzmebi', 'Dental', 'Varketili', 'Varketili Massive, 5 M/R Korp. 2', '73 13 22', 'kbilebi.com', 'new', 'medium'),
  ('Jeodenti', 'Dental', 'Gldani', 'A M/R Korp. 50', '65 63 56', 'kbilebi.com', 'new', 'medium'),
  ('HBI-Denti', 'Dental', 'Saburtalo', 'Mitskevich St. 20', '37 96 70', 'kbilebi.com', 'new', 'medium'),
  ('Helsi Denti', 'Dental', 'Sololaki', 'Sulkhan-Saba St. 9', '99 77 73', 'kbilebi.com', 'new', 'medium');

-- Batch 4: rows 151-200
INSERT INTO leads (name, category, district, address, phone, source, status, priority) VALUES
  ('Holivudi', 'Dental', 'Mtatsminda', 'Laghidze St. 6', '99 98 54', 'kbilebi.com', 'new', 'medium'),
  ('Holivud Smile', 'Dental', 'Saburtalo', 'Vazha-Pshavela Ave. 35', '47 70 00', 'kbilebi.com', 'new', 'medium'),
  ('Hefi Smile', 'Dental', 'Saburtalo', 'D. Gamrekeli St. 19', '37 55 25', 'kbilebi.com', 'new', 'medium'),
  ('Heliodenti', 'Dental', 'Saburtalo', 'Brolosani St. 25/27 N2', '2-43 13 13, 598-75 13 33', 'kbilebi.com', 'new', 'medium'),
  ('Nino Kardava Dental Clinic', 'Dental', 'Saburtalo', 'Petra Kavtaradze St. 58', NULL, 'madloba.info', 'new', 'medium'),
  ('Dentor', 'Dental', 'Saburtalo', 'Alexander Kazbegi Ave. 28', NULL, 'madloba.info', 'new', 'medium'),
  ('Modern Dental', 'Dental', 'Saburtalo', 'Bakhtrioni St. 24', NULL, 'madloba.info', 'new', 'medium'),
  ('Dental Line', 'Dental', 'Avlabari', 'Vakhtanga Gorgasali St. 63', NULL, 'madloba.info', 'new', 'medium'),
  ('Zeppelin', 'Dental', 'Didube', 'Sergo Zakariadze St. 15', NULL, 'madloba.info', 'new', 'medium'),
  ('Evergreen', 'Dental', 'Saburtalo', 'Zurab Sakandelidze St. 19', NULL, 'madloba.info', 'new', 'medium'),
  ('In Vera Dent', 'Dental', 'Vera', '24 Vasil Barnov Street', NULL, 'smilehub.ge', 'new', 'medium'),
  ('Nei Dent', 'Dental', 'Chugureti', '53 Kote Marjanishvili Square', NULL, 'smilehub.ge', 'new', 'medium'),
  ('Dea Dent', 'Dental', 'Didube', '3 Kipiani St.', '(593) 60 01 09', 'yell.ge', 'new', 'medium'),
  ('Dental-Studio', 'Dental', 'Varketili', '22 Kaloubani St.', '(593) 01 73 73', 'yell.ge', 'new', 'medium'),
  ('Dentor - Ia Isadze', 'Dental', 'Saburtalo', '28 Kazbegi Ave.', '+995 571 101 100', 'yell.ge', 'new', 'medium'),
  ('Ekaterine Khidasheli Dental', 'Dental', 'Gldani', 'A M/D, B. 50', '(595) 59 99 06', 'yell.ge', 'new', 'medium'),
  ('Esthedent', 'Dental', 'Vera', '2 Sative St.', '(568) 34 12 12, (599) 36 12 12', 'yell.ge', 'new', 'medium'),
  ('Kakhaber Tsiklauri Dental', 'Dental', 'Samgori', '46/28 Moscow Ave.', '270 69 57', 'yell.ge', 'new', 'medium'),
  ('Leader Dental International', 'Dental', 'Vera', '2 Tarkhnishvili St.', '230 60 66, (599) 30 60 86', 'yell.ge', 'new', 'medium'),
  ('Life Dent', 'Dental', 'Saburtalo', '24 Burdzgla St.', '237 80 90, (596) 30 00 60', 'yell.ge', 'new', 'medium'),
  ('M. Tatishvili Dental Spa', 'Dental', 'Saburtalo', '3 Z. Anjaparidze I turn', '220 13 20, 236 81 56', 'yell.ge', 'new', 'medium'),
  ('MBS', 'Dental', 'Samgori', '5 Moscow Ave.', '270 22 23', 'yell.ge', 'new', 'medium'),
  ('New Smile Dental Center', 'Dental', 'Chugureti', '21 Gorki St.', '245 00 65', 'yell.ge', 'new', 'medium'),
  ('Phoenix', 'Dental', 'Didube', '121 Tsereteli Ave.', '234 00 33, (596) 34 00 33', 'yell.ge', 'new', 'medium'),
  ('Solo Clinic', 'Dental', 'Sololaki', '14 Leonidze St.', '(599) 87 87 11, 211 00 30', 'yell.ge', 'new', 'medium'),
  ('Beautify Aesthetic Studio', 'Aesthetic', 'Saburtalo', '13o Tamarashvili St.', '(514) 20 77 00', 'yell.ge', 'new', 'medium'),
  ('Esthetic Centre', 'Aesthetic', 'Saburtalo', '26 Bakhtrioni St.', '(599) 93 24 07', 'yell.ge', 'new', 'medium'),
  ('Clinic Arya', 'Aesthetic', 'Saburtalo', '34 Kazbegi Ave.', '(579) 22 11 53', 'yell.ge', 'new', 'medium'),
  ('Endorphin Clinic', 'Aesthetic', 'Mukhiani', '15b Gobronidze St.', '(574) 268 268', 'yell.ge', 'new', 'medium'),
  ('Art Aesthetic', 'Aesthetic', 'Saburtalo', '2 Tsintsadze St.', '(574) 405 414', 'yell.ge', 'new', 'medium'),
  ('Body Room', 'Aesthetic', 'Vake', '10 Paliashvili St.', '(555) 46 99 30', 'yell.ge', 'new', 'medium'),
  ('Body Style', 'Aesthetic', 'Saburtalo', '18 Gamrekeli St.', '(597) 44 50 11', 'yell.ge', 'new', 'medium'),
  ('La Femme - Khatia Iarajuli', 'Aesthetic', 'Saburtalo', '48 Kavtaradze St.', '(593) 37 02 30', 'yell.ge', 'new', 'medium'),
  ('Diamond Aesthetic', 'Aesthetic', 'Gldani', '8 I. Vekua St.', '(555) 00 08 06', 'yell.ge', 'new', 'medium'),
  ('Sani Dental Clinic & Aesthetic', 'Aesthetic', 'Didi Digomi', '106 Mirian Mepe St.', '(596) 441 441', 'yell.ge', 'new', 'medium'),
  ('Kani Aesthetic', 'Aesthetic', 'Saburtalo', '11 Saakadze Descent', '218 18 18, 243 40 00', 'yell.ge', 'new', 'medium'),
  ('Eka Bukhrashvili Dental Aesthetic', 'Aesthetic', 'Nadzaladevi', '207 Ts. Dadiani St.', '(557) 77 04 06, (599) 330 370', 'yell.ge', 'new', 'medium'),
  ('Drops Wellness', 'Aesthetic', 'Vake', '48 I. Abashidze St.', '223 53 53', 'yell.ge', 'new', 'medium'),
  ('New Vision Health Hub', 'Aesthetic', 'Digomi', '9 N. Bokhua St.', '219 49 90', 'yell.ge', 'new', 'medium'),
  ('Fit Line', 'Aesthetic', 'Saburtalo', '39 Tsintsadze St.', '(593) 95 59 19', 'yell.ge', 'new', 'medium'),
  ('MedCapital Esthetics', 'Aesthetic', 'Gldani', '18 I. Vekua St., fl. 4', '(595) 01 82 36', 'yell.ge', 'new', 'medium'),
  ('Botanic', 'Aesthetic', 'Vake', '8 Mosashvili St.', '225 35 20', 'yell.ge', 'new', 'medium'),
  ('Best Care', 'Aesthetic', 'Chugureti', '10 Saint Petersburg St.', '(511) 23 77 78', 'yell.ge', 'new', 'medium'),
  ('Beauty Centre Annia', 'Aesthetic', 'Didi Digomi', '4 Petre Iberi St.', '(551) 25 00 50, (577) 79 38 88', 'yell.ge', 'new', 'medium'),
  ('Javakhishvili Cosmetic Clinic', 'Aesthetic', 'Vake', '19 Kekelidze St.', '225 21 36, (599) 11 67 76', 'yell.ge', 'new', 'medium'),
  ('Skin Care', 'Aesthetic', 'Chugureti', '168 Agmashenebeli Ave.', '(555) 72 20 33', 'yell.ge', 'new', 'medium'),
  ('MB Aesthetics House', 'Aesthetic', 'Didube', '13 T. Eristavi St.', '(591) 21 00 02, 290 42 16', 'yell.ge', 'new', 'medium'),
  ('Ia Darsavelidze Clinic', 'Aesthetic', 'Saburtalo (Vedzisi)', '19/2 Gagarin St.', '2 225 335, (555) 80 60 60', 'yell.ge', 'new', 'medium'),
  ('EG Beauty Boutique', 'Aesthetic', 'Didi Digomi', '3 Ian Homeri St.', '(557) 766 863', 'yell.ge', 'new', 'medium'),
  ('Studio Lini', 'Aesthetic', 'Vake', '9 Arakishvili St.', '222 02 12, (571) 22 02 12', 'yell.ge', 'new', 'medium');

-- Batch 5: rows 201-250
INSERT INTO leads (name, category, district, address, phone, source, status, priority) VALUES
  ('New Paris', 'Aesthetic', 'Vake', '17 Paliashvili St.', '225 30 91, (579) 17 33 66', 'yell.ge', 'new', 'medium'),
  ('Femina', 'Aesthetic', 'Saburtalo', '24 University St., Greenhill', '(555) 28 70 00', 'yell.ge', 'new', 'medium'),
  ('Beauty Salon Gracia', 'Aesthetic', 'Digomi', 'Robakidze Ave., Q. 2, B. 6b', '251 70 30, (599) 50 46 93', 'yell.ge', 'new', 'medium'),
  ('Dermamed', 'Dermatology', 'Nadzaladevi', '134 Ts. Dadiani St.', '269 61 59, (593) 62 53 07', 'yell.ge', 'new', 'medium'),
  ('Genesis Clinic', 'Aesthetic', 'Saburtalo', '70a Vazha-Pshavela Ave.', '283 30 31, (591) 50 27 27', 'yell.ge', 'new', 'medium'),
  ('Beauty Salon Fantasy', 'Aesthetic', 'Didube', '55 Tsereteli Ave.', '235 22 76, (599) 20 47 92', 'yell.ge', 'new', 'medium'),
  ('Aesthetics', 'Aesthetic', 'Vake', '17 I. Abashidze St.', '(591) 23 01 23', 'yell.ge', 'new', 'medium'),
  ('Beauty Secret', 'Aesthetic', 'Saburtalo', '9 Tamarashvili St.', '(551) 12 44 22, (595) 25 11 30', 'yell.ge', 'new', 'medium'),
  ('Aesthetic Corner', 'Aesthetic', 'Vera', '5 I. Nikoladze St.', '229 56 61, (593) 31 96 34', 'yell.ge', 'new', 'medium'),
  ('Beauty Salon Merlin', 'Aesthetic', 'Varketili', 'Varketili 3, IV M/D, B. 416', '(555) 47 14 44', 'yell.ge', 'new', 'medium'),
  ('Esthetic Center Leader', 'Aesthetic', 'Gldani', '1 I. Vekua St.', '265 27 83, 218 51 51', 'yell.ge', 'new', 'medium'),
  ('Premier Spa / Dibi Milano', 'Aesthetic', 'Vake', '22 Mukhadze St.', '(591) 44 00 32', 'yell.ge', 'new', 'medium'),
  ('Aesthetic Clinic Neo-Neo', 'Aesthetic', 'Saburtalo', 'Bakhtrioni str. 11B', NULL, 'madloba.info', 'new', 'medium'),
  ('Skin Code', 'Aesthetic', 'Vake', '66 Paliashvili St.', NULL, 'madloba.info', 'new', 'medium'),
  ('Victoria', 'Aesthetic', 'Saburtalo', '7 Alexandra Kazbegi Ave.', NULL, 'madloba.info', 'new', 'medium'),
  ('Aesthetic Clinic 27', 'Aesthetic', 'Vake', '118 Zakaria Paliashvili St.', NULL, 'madloba.info', 'new', 'medium'),
  ('Woman and Health', 'Aesthetic', 'Vake', '8 I. Mosashvili St.', '(595) 00 15 89', 'madloba.info', 'new', 'medium'),
  ('Unica', 'Aesthetic', 'Vake', '24 I. Chavchavadze Ave.', NULL, 'madloba.info', 'new', 'medium'),
  ('Line Clinic', 'Aesthetic', 'Saburtalo', '166/2 Otara Chiladze St.', NULL, 'madloba.info', 'new', 'medium'),
  ('Inexmed', 'Aesthetic', 'Isani', '41/6 Ketevan Dedopali', NULL, 'madloba.info', 'new', 'medium'),
  ('Skin Medical', 'Aesthetic', 'Saburtalo', '2 V. Chabukiani St.', NULL, 'madloba.info', 'new', 'medium'),
  ('KnowHow Beauty Centre', 'Aesthetic', 'Saburtalo', '11b Bakhtrioni St.', '224 14 44, (596) 24 22 44', 'yell.ge', 'new', 'medium'),
  ('Club 71', 'Aesthetic', 'Vake', '71 Vazha-Pshavela Ave.', '+995 322 20 00 71', 'madloba.info', 'new', 'medium'),
  ('Gaga Lapanashvili Clinic', 'Aesthetic', 'Varketili', 'Javakheti I Lane, B. 9', '(555) 23 47 74', 'yell.ge', 'new', 'medium'),
  ('Dadvani Center', 'Aesthetic', 'Saburtalo', '25b Adam Mitskevichi St.', NULL, 'whatclinic', 'new', 'medium'),
  ('Aesthetic Centre Mzeana', 'Aesthetic', 'Didube', '3a Mirtskhulava St.', '(571) 48 44 22, (595) 74 79 60', 'yell.ge', 'new', 'medium'),
  ('Clinic Medside', 'Medical', 'Gldani', '2a Vasadze St.', '(597) 00 44 22, 220 65 65', 'yell.ge', 'new', 'medium'),
  ('Esthetic Studio #8', 'Aesthetic', 'Digomi', '8 Akhmeteli St.', '206 08 08, (568) 08 08 80', 'yell.ge', 'new', 'medium'),
  ('4 Seasons Esthetics', 'Aesthetic', 'Digomi', 'Digomi Massive, Q. 6, B. 20', '201 14 14, (591) 52 14 14', 'yell.ge', 'new', 'medium'),
  ('Aesthetic and Beauty Centre', 'Aesthetic', 'Saburtalo', '25b Mitskevich St.', '222 73 27', 'yell.ge', 'new', 'medium'),
  ('Aesthetic Center Epigold', 'Aesthetic', 'Saburtalo', '17 Kazbegi Ave.', '(558) 10 25 25', 'yell.ge', 'new', 'medium'),
  ('Aesthetic Gallery', 'Aesthetic', 'Didi Digomi', '6 Avtandil St.', '(591) 854 854', 'yell.ge', 'new', 'medium'),
  ('Aesthetic House VIP Laser', 'Aesthetic', 'Gldani', '4 Vasadze St.', '(579) 00 80 20', 'yell.ge', 'new', 'medium'),
  ('Aesthetic Medcenter Image Factory', 'Aesthetic', 'Saburtalo', '14 Kazbegi Ave.', '(571) 28 00 83', 'yell.ge', 'new', 'medium'),
  ('Aesthetic Room', 'Aesthetic', 'Sanzona', '1e Gudamakari St.', '(593) 57 49 57', 'yell.ge', 'new', 'medium'),
  ('Panderma', 'Dermatology', 'Saburtalo', '24 University St.', '2 007 008', 'yell.ge', 'new', 'medium'),
  ('David Telia Clinic', 'Dermatology', 'Saburtalo', '36 Vazha-Pshavela Ave.', '222 82 83', 'yell.ge', 'new', 'medium'),
  ('Adori Dermatological Clinic', 'Dermatology', 'Saburtalo', '5 Ana Kalandadze St.', '(551) 98 40 20, (595) 59 40 20', 'yell.ge', 'new', 'medium'),
  ('Dermaven+', 'Dermatology', 'Chugureti', '7a G. Kancheli St.', '(593) 25 97 94, (599) 57 29 69', 'yell.ge', 'new', 'medium'),
  ('Dermatology and Aesthetic Clinic', 'Dermatology', 'Gldani', '2 Marseille St., C1', '(596) 38 77 38', 'yell.ge', 'new', 'medium'),
  ('Dr. Gocha Kimutsadze', 'Dermatology', 'Saburtalo (Vedzisi)', '8 Panjikidze St.', '(599) 19 79 13', 'yell.ge', 'new', 'medium'),
  ('Aesthetics Centre Art Studio', 'Dermatology', 'Vake', '3 Paliashvili St.', '243 55 17, (551) 18 17 87', 'yell.ge', 'new', 'medium'),
  ('Aino - Ozone Therapy Clinic', 'Medical', 'Saburtalo', '39 Shartava St.', '(551) 53 40 41', 'yell.ge', 'new', 'medium'),
  ('AM Clinic', 'Medical', 'Saburtalo', '1a Mirotadze St.', '(511) 30 03 55, (568) 28 28 25', 'yell.ge', 'new', 'medium'),
  ('Children''s Polyclinic N02', 'Medical', 'Didube', 'T. Eristavi St. 3', '322 690 346', 'city24.ge', 'new', 'medium'),
  ('Children''s Polyclinic N06', 'Medical', 'Nadzaladevi', 'I. Pagava St. 25', '322 747 555', 'city24.ge', 'new', 'medium'),
  ('Children''s Polyclinic N07', 'Medical', 'Nadzaladevi', 'Bogdan Khmelnitski St. 153a', '322 274 035', 'city24.ge', 'new', 'medium'),
  ('Children''s Polyclinic N16', 'Medical', 'Saburtalo', 'A. Benashvili St. 3', '322 955 909', 'city24.ge', 'new', 'medium'),
  ('Children''s Polyclinic N22', 'Medical', 'Nadzaladevi', 'N. Buachidze St. 12', '322 613 103', 'city24.ge', 'new', 'medium'),
  ('Children''s Polyclinic N24', 'Medical', 'Avchala', 'Libani St. 1', '577 411 079', 'city24.ge', 'new', 'medium');

-- Batch 6: rows 251-300
INSERT INTO leads (name, category, district, address, phone, source, status, priority) VALUES
  ('Children''s Polyclinic #21', 'Medical', 'Digomi', 'Digomi Massive, Q. 5, B. 5a', '252 29 98', 'yell.ge', 'new', 'medium'),
  ('Polyclinic for Adults N01', 'Medical', 'Nadzaladevi', 'Ts. Dadiani St. 321', '322 690 763', 'city24.ge', 'new', 'medium'),
  ('Polyclinic for Adults N02', 'Medical', 'Nadzaladevi', 'Ts. Dadiani St. 20', '322 951 525', 'city24.ge', 'new', 'medium'),
  ('Polyclinic for Adults N13', 'Medical', 'Mtatsminda', 'Rustaveli Ave. 28', '322 998 195', 'city24.ge', 'new', 'medium'),
  ('Polyclinic for Adults N26', 'Medical', 'Saburtalo', 'Vazha-Pshavela Ave. 26', '322 390 417', 'city24.ge', 'new', 'medium'),
  ('Polyclinic for Adults N27', 'Medical', 'Gldani', 'Ilori St. 14', '322 650 835', 'city24.ge', 'new', 'medium'),
  ('Polyclinic for Adults N29', 'Medical', 'Avchala', 'Libani St. 3', '322 629 143', 'city24.ge', 'new', 'medium'),
  ('Polyclinic for Adults #19', 'Medical', 'Samgori', '23 Moscow Ave.', '271 68 91', 'yell.ge', 'new', 'medium'),
  ('Polyclinic #1', 'Medical', 'Nadzaladevi', '23 Bezhanishvili St.', '(592) 42 30 03', 'yell.ge', 'new', 'medium'),
  ('Family Medicine Centre N3', 'Medical', 'Didube', 'A. Tsereteli Ave. 138', '322 341 030', 'city24.ge', 'new', 'medium'),
  ('Family Medicine Center Isani', 'Medical', 'Isani', '1 Junkers St.', '274 87 65', 'yell.ge', 'new', 'medium'),
  ('Family Medicine Center #4', 'Medical', 'Vazisubani', 'IV M/D, Q. 1', '278 24 90', 'yell.ge', 'new', 'medium'),
  ('Family Medicine Centre #2', 'Medical', 'Didube', '3 T. Eristavi St.', '269 03 46', 'yell.ge', 'new', 'medium'),
  ('Family Doctor', 'Medical', 'Chugureti', '6 Khetagurov St.', '295 88 64', 'yell.ge', 'new', 'medium'),
  ('Mkurnali 99', 'Medical', 'Chugureti', 'K. Khetagurovi St. 6', '322 957 220', 'city24.ge', 'new', 'medium'),
  ('Diabetes Research National Centre', 'Medical', 'Digomi', '1 Chachava St.', '272 90 81', 'yell.ge', 'new', 'medium'),
  ('Georgian-American Diagnostic Clinic', 'Medical', 'Saburtalo', '3 Gotua St.', '243 00 73', 'yell.ge', 'new', 'medium'),
  ('Kavtasi Clinic', 'Medical', 'Saburtalo', '32a Kazbegi Ave.', '(595) 26 32 17', 'yell.ge', 'new', 'medium'),
  ('Medsi Clinic', 'Medical', 'Vera', '47/57 Kostava St.', '(032) 2 15 78 77', 'yell.ge', 'new', 'medium'),
  ('Alexander Aladashvili Clinic', 'Medical', 'Chugureti', '103 Uznadze St.', '295 80 14', 'yell.ge', 'new', 'medium'),
  ('Teomedi - Endoscopy Center', 'Medical', 'Saburtalo', '14b Kazbegi Ave.', '222 72 86', 'yell.ge', 'new', 'medium'),
  ('Premium Medi', 'Medical', 'Sanzona', '2 N. Buachidze St.', '(599) 56 54 80', 'yell.ge', 'new', 'medium'),
  ('Status Clinic', 'Medical', 'Digomi', '13d Ljubljana St.', '032 211 40 40', 'yell.ge', 'new', 'medium'),
  ('Raymann Clinic', 'Medical', 'Saburtalo', '7 S. Euli St.', '212 11 22', 'yell.ge', 'new', 'medium'),
  ('Old Avlabari Medical Centre', 'Medical', 'Avlabari', '25 Pagava St.', '274 75 55', 'yell.ge', 'new', 'medium'),
  ('Medical Centre First', 'Medical', 'Nadzaladevi', '10 Khudadov St.', '295 34 06', 'yell.ge', 'new', 'medium'),
  ('Medical-Prophylactic Center #3', 'Medical', 'Chugureti', '7 Z. Chavchavadze St.', '295 08 26', 'yell.ge', 'new', 'medium'),
  ('MMEDI22', 'Medical', 'Sanzona', '16a N. Buachidze St.', '(591) 57 55 33', 'yell.ge', 'new', 'medium'),
  ('Medical Centre #8', 'Medical', 'Avlabari', '13 Shiraki St.', '274 83 71', 'yell.ge', 'new', 'medium'),
  ('Dastakari', 'Medical', 'Digomi', 'Vill. Digomi, 83 Agmashenebeli St.', '(599) 43 23 43', 'yell.ge', 'new', 'medium'),
  ('Janmrteloba', 'Medical', 'Ponichala', 'Upper Ponichala, B. 20', '275 09 36', 'yell.ge', 'new', 'medium'),
  ('Lilo Medical Centre', 'Medical', 'Lilo', '19 Pranguliani St.', '274 14 92', 'yell.ge', 'new', 'medium'),
  ('Medical Centre Diomedi', 'Medical', 'Saburtalo', '15a Tamarashvili St.', '292 25 01', 'yell.ge', 'new', 'medium'),
  ('Unica Medical', 'Medical', 'Ortachala', '8 Gorgasali St.', '(592) 20 20 64', 'yell.ge', 'new', 'medium'),
  ('Health Center', 'Medical', 'Saburtalo', '14b Kazbegi Ave.', '214 44 05', 'yell.ge', 'new', 'medium'),
  ('St. Ioakime and Anna Medical Centre', 'Medical', 'Ortachala', '95 Gorgasali St.', '275 57 57', 'yell.ge', 'new', 'medium'),
  ('Ivane Bokeria University Hospital', 'Medical', 'Samgori', '8 Zurab Iarajuli St.', '280 16 00', 'yell.ge', 'new', 'medium'),
  ('Tbilisi Central Hospital', 'Medical', 'Digomi', '1 Chachava St. / 5 Ljubljana St.', '210 44 44', 'yell.ge', 'new', 'medium'),
  ('Gudushauri Clinic', 'Medical', 'Digomi', '66 Ljubljana St.', '251 87 15', 'yell.ge', 'new', 'medium'),
  ('Georgian Dutch Hospital', 'Medical', 'Mukhiani', '27 Gobronidze St.', '(591) 54 05 00', 'yell.ge', 'new', 'medium'),
  ('Kalantarov Clinic', 'Plastic Surgery', 'Digomi', '4 Givi Zhvania St.', '(577) 22 99 22', 'yell.ge', 'new', 'medium'),
  ('Renew Plastic Surgery', 'Plastic Surgery', 'Digomi', '1 Tereverko I turn', '(597) 03 03 00', 'yell.ge', 'new', 'medium'),
  ('Plastic Aesthetic Surgery Clinic', 'Plastic Surgery', 'Digomi', '1 Chachava St.', '(577) 40 17 28', 'yell.ge', 'new', 'medium'),
  ('Kuzanov Clinic', 'Plastic Surgery', 'Saburtalo', '5 Peking St.', '242 40 05', 'yell.ge', 'new', 'medium'),
  ('Total Charm', 'Plastic Surgery', 'Mtatsminda', '18 Orbeliani St.', '218 18 14', 'yell.ge', 'new', 'medium'),
  ('Prestige', 'Beauty', 'Gldani', 'Near S/S Akhmeteli', '265 28 79', 'yell.ge', 'new', 'medium'),
  ('Beauty Salon Misel', 'Beauty', 'Vake', '39a Paliashvili St.', '(577) 58 88 77', 'yell.ge', 'new', 'medium'),
  ('Eleonora', 'Beauty', 'Vake', '6 R. Eristavi St.', '(599) 27 04 66', 'yell.ge', 'new', 'medium'),
  ('Beauty In', 'Beauty', 'Saburtalo (Delisi)', '3 Gazapkhuli St.', '(558) 13 30 00', 'yell.ge', 'new', 'medium'),
  ('Style', 'Beauty', 'Gldani', 'Near S/S Akhmeteli', '(551) 00 77 22', 'yell.ge', 'new', 'medium');

-- Batch 7: rows 301-350
INSERT INTO leads (name, category, district, address, phone, source, status, priority) VALUES
  ('Rafael', 'Beauty', 'Vake', '61 I. Abashidze St.', '(577) 14 88 88', 'yell.ge', 'new', 'medium'),
  ('Mia', 'Beauty', 'Chugureti', '92 Tsinamdzgvrishvili St.', '295 23 13', 'yell.ge', 'new', 'medium'),
  ('Ia XXI', 'Beauty', 'Chugureti', '25 Marjanishvili St.', '294 25 30, (555) 61 13 31', 'yell.ge', 'new', 'medium'),
  ('Belissimo', 'Beauty', 'Saburtalo', '69 Vazha-Pshavela Ave.', '(579) 02 08 79', 'yell.ge', 'new', 'medium'),
  ('Hebe', 'Beauty', 'Vake', '4 Mtskheta St.', '243 20 25, (599) 53 01 39', 'yell.ge', 'new', 'medium'),
  ('Beauty Salon Lux', 'Beauty', 'Gldani', '13 K. Leselidze St.', '243 00 02', 'yell.ge', 'new', 'medium'),
  ('Beauty Time', 'Beauty', 'Vera', '8 Chovelidze St.', '(599) 15 56 24', 'yell.ge', 'new', 'medium'),
  ('Bon Vivant', 'Beauty', 'Saburtalo', '193 Nutsubidze St.', '(514) 10 90 70', 'yell.ge', 'new', 'medium'),
  ('Lazholi', 'Beauty', 'Saburtalo', '4 Kazbegi Ave.', '238 11 81', 'yell.ge', 'new', 'medium'),
  ('Fusion', 'Beauty', 'Sololaki', '18 Leonidze St.', '299 72 46', 'yell.ge', 'new', 'medium'),
  ('Elita', 'Beauty', 'Saburtalo', '11/4 Dolidze St.', '233 56 06', 'yell.ge', 'new', 'medium'),
  ('Art-Style', 'Beauty', 'Chugureti', '3 Saint Petersburg St.', '(593) 33 77 93', 'yell.ge', 'new', 'medium'),
  ('Sabrina', 'Beauty', 'Ortachala', '39 Gorgasali St.', '272 30 00, (598) 72 30 00', 'yell.ge', 'new', 'medium'),
  ('In Vogue Beauty Salon', 'Beauty', 'Chugureti', '6 Khetagurov St.', '296 75 71, (574) 34 44 22', 'yell.ge', 'new', 'medium'),
  ('Massage Center Serafiti', 'Beauty', 'Saburtalo', '8a Al. Kazbegi Ave.', '558 212 755', 'city24.ge', 'new', 'medium'),
  ('Aisha', 'Beauty', 'Nadzaladevi', '22 Ts. Dadiani St.', '322 436 812', 'city24.ge', 'new', 'medium'),
  ('KN Beauty House', 'Beauty', 'Saburtalo', '34 J. Shartava St.', '571 997 777', 'city24.ge', 'new', 'medium'),
  ('Artonomia', 'Beauty', 'Saburtalo', '10a Mirotadze St.', '(599) 86 82 82', 'yell.ge', 'new', 'medium'),
  ('T & L', 'Beauty', 'Nadzaladevi', '105 Ts. Dadiani St.', '269 40 50', 'yell.ge', 'new', 'medium'),
  ('Diadenti (FB only)', 'Dental', 'Saburtalo', 'I. Nikoladze St. 7', '+995 322 10 30 50', 'Facebook', 'new', 'medium'),
  ('Dental Clinic GT (FB only)', 'Dental', 'Isani', 'Navtlughis 5/7', '+995 599 06 11 19', 'Facebook', 'new', 'medium'),
  ('FF Dental Clinic (FB only)', 'Dental', 'Gldani', 'Gldani', '+995 555 56 16 13', 'Facebook', 'new', 'medium'),
  ('Teoline Dental Esthetic (FB only)', 'Dental', 'Saburtalo', 'B. Kvernadze St. 20', '+995 591 93 14 14', 'Facebook', 'new', 'medium'),
  ('Meta Prime Dental (FB only)', 'Dental', 'Saburtalo', 'Sandro Euli St. 5', '+995 32 220 13 20', 'Facebook', 'new', 'medium'),
  ('Solid Dental Group (FB only)', 'Dental', 'Vera', 'Kostava St. 63', '+995 571 70 01 00', 'Facebook', 'new', 'medium'),
  ('Innova Dental & Aesthetic (FB only)', 'Dental', 'Didube', '141a Tsereteli Ave.', '+995 577 47 53 33', 'Facebook', 'new', 'medium'),
  ('Dr. Natalia Aesthetics (FB only)', 'Aesthetic', 'Saburtalo', '46 Adam Mitskevichi St.', '557 333 077', 'Facebook', 'new', 'medium'),
  ('Esthetics Center Nefertiti (FB only)', 'Aesthetic', 'Tbilisi', NULL, NULL, 'Facebook', 'new', 'medium'),
  ('Booster Beauty Aesthetic Lab (FB only)', 'Aesthetic', 'Tbilisi', NULL, NULL, 'Facebook', 'new', 'medium'),
  ('Viva Aesthetics (FB only)', 'Aesthetic', 'Tbilisi', NULL, NULL, 'Facebook', 'new', 'medium'),
  ('Aesthetic Center Misel (FB only)', 'Aesthetic', 'Tbilisi', NULL, NULL, 'Facebook', 'new', 'medium'),
  ('NM Esthetic Center (FB only)', 'Aesthetic', 'Tbilisi', NULL, NULL, 'Facebook', 'new', 'medium'),
  ('Karisma Esthetic Center (FB only)', 'Aesthetic', 'Tbilisi', NULL, NULL, 'Facebook', 'new', 'medium'),
  ('Painful Art Tattoo Piercing Studio', 'Tattoo', 'Mtatsminda', '14 Rustaveli Ave.', '(591) 41 43 61', 'yell.ge', 'new', 'medium'),
  ('Indigo Cat Tattoo Studio', 'Tattoo', 'Chugureti', '83 Agmashenebeli Ave.', '(597) 96 30 94', 'Facebook', 'new', 'medium'),
  ('Zona Tattoo & Piercing', 'Tattoo', 'Vera', '8 I. Nikoladze St.', '(585) 88 88 17', 'Instagram', 'new', 'medium'),
  ('Tolik Tattoo', 'Tattoo', 'Saburtalo', '12 Gamrekeli St.', '(593) 48 42 51', 'yell.ge', 'new', 'medium'),
  ('Tattoo Studio Eduard Fish', 'Tattoo', 'Saburtalo', '4 Gamrekeli St.', '(557) 16 99 64', 'yell.ge', 'new', 'medium'),
  ('Jankhotely Tattoo Gallery', 'Tattoo', 'Didube', '3a Mirtskhulava St.', '(593) 31 51 85', 'yell.ge', 'new', 'medium'),
  ('Black Kiss Tattoo Studio', 'Tattoo', 'Saburtalo', '32 Vazha-Pshavela Ave.', '(555) 10 99 72', 'Instagram', 'new', 'medium'),
  ('Picasso Tattoo', 'Tattoo', 'Saburtalo', '2 Peking St.', '(555) 51 08 08', 'yell.ge', 'new', 'medium'),
  ('Ink Kiss Tattoo Studio', 'Tattoo', 'Mtatsminda', '37 Rustaveli Ave.', '(568) 42 50 84', 'Instagram', 'new', 'medium'),
  ('Diamond Dog Tattoo', 'Tattoo', 'Saburtalo', '166/2 O. Chiladze St.', '(555) 99 56 07', 'yell.ge', 'new', 'medium'),
  ('DMS Beauty Centre (tattoo)', 'Tattoo', 'Didi Digomi', '84a Mirian Mepe St.', '219 26 46', 'yell.ge', 'new', 'medium'),
  ('ADIT Tattoo', 'Tattoo', 'Avlabari', '12 St. Queen Ketevan Ave.', '277 24 74, (571) 34 87 77', 'yell.ge', 'new', 'medium'),
  ('Crystal Tattoo', 'Tattoo', 'Saburtalo', '49 Tsintsadze St.', '214 19 19, (577) 60 19 19', 'yell.ge', 'new', 'medium'),
  ('Perforator Tattoo Studio', 'Tattoo', 'Saburtalo', '44/1 Shalva Nutsubidze St.', NULL, 'Instagram', 'new', 'medium'),
  ('Inkwell Tattoo Studio', 'Tattoo', 'Chugureti', '8 M. Gogiberidze St.', NULL, 'Facebook', 'new', 'medium'),
  ('Portal Tattoos & Piercing', 'Tattoo', 'Chugureti', '53 Dimitri Uznadze St.', NULL, 'Facebook', 'new', 'medium'),
  ('Totoshka Tattoo Studio', 'Tattoo', 'Chugureti', '4 Otar Taktakishvili St.', NULL, 'TripAdvisor', 'new', 'medium');

-- Batch 8: rows 351-400
INSERT INTO leads (name, category, district, address, phone, source, status, priority) VALUES
  ('Tattoo 13 Tbilisi', 'Tattoo', 'Saburtalo', '3 Petra Kobakhidze St.', NULL, 'Maps', 'new', 'medium'),
  ('Linka Tattoo Studio', 'Tattoo', 'Saburtalo', '16 Andrei Benashvili St.', NULL, 'Instagram', 'new', 'medium'),
  ('MobisTattoo', 'Tattoo', 'Saburtalo', '12a A. Weretzky Ave.', '557 10 91 09', 'Maps', 'new', 'medium'),
  ('Regisi Tattoo', 'Tattoo', 'Saburtalo', '12 Bakhtrionis St.', '322 72 82 87', 'Maps', 'new', 'medium'),
  ('Lucky Boyz Studio (LBS)', 'Tattoo', 'Saburtalo', '49 Sulkhan Tsintsadze St.', NULL, 'Facebook', 'new', 'medium'),
  ('Cover Tattoo', 'Tattoo', 'Vera', '2 Lev Tolstoy St.', NULL, 'Maps', 'new', 'medium'),
  ('NV Studio Tattoo', 'Tattoo', 'Vera', '3 Louis Pasteur St.', NULL, 'Maps', 'new', 'medium'),
  ('Louie''s Tattoo Studio', 'Tattoo', 'Saburtalo', '10 Vazha-Pshavela Ave.', NULL, 'Maps', 'new', 'medium'),
  ('Tattoo Room Tbilisi', 'Tattoo', 'Vera', '7 Merab Kostava St.', NULL, 'Maps', 'new', 'medium'),
  ('Dot Tattoo Studio', 'Tattoo', 'Vake', '8a Dimitri Arakishvili St.', NULL, 'Maps', 'new', 'medium'),
  ('BTN Pro-Fashional', 'Tattoo', 'Vake', '7 Kipshidze St.', NULL, 'Maps', 'new', 'medium'),
  ('Manuscript Tattoo', 'Tattoo', 'Chugureti', '106/14 Agmashenebeli Ave.', NULL, 'Maps', 'new', 'medium'),
  ('Tattoo Studio King''s', 'Tattoo', 'Vake', '52 Zakaria Paliashvili St.', NULL, 'Maps', 'new', 'medium'),
  ('Permanent Makeup by Nino', 'Tattoo', 'Saburtalo', '73 Tsintsadze St.', NULL, 'Maps', 'new', 'medium'),
  ('Avangard Tattoo Studio', 'Tattoo', 'Gldani', '70 Atskuri St.', NULL, 'Maps', 'new', 'medium'),
  ('Valkyrie Tattoo Studio', 'Tattoo', 'Gldani', '12/17 Shindiseli Gmiris St.', NULL, 'Maps', 'new', 'medium'),
  ('Pulp Fiction Tattoo Studio', 'Tattoo', 'Vera', '23 Tamar Chovelidze St.', NULL, 'Maps', 'new', 'medium'),
  ('Hobbiton Tattoo Studio', 'Tattoo', 'Saburtalo', '59b Tsintsadze St.', NULL, 'Maps', 'new', 'medium'),
  ('1st Edition Ink', 'Tattoo', 'Saburtalo', '38 Tsintsadze St.', NULL, 'Maps', 'new', 'medium'),
  ('Shavi Verdzi Tattoo', 'Tattoo', 'Saburtalo', '4 Simon Janashia St.', NULL, 'Maps', 'new', 'medium'),
  ('Luna Ink Studio', 'Tattoo', 'Saburtalo', '16 Sarkinetis St.', NULL, 'Maps', 'new', 'medium'),
  ('LUMA Tattoo & Piercing', 'Tattoo', 'Saburtalo', '4 Romanoz Khomleli St.', NULL, 'Maps', 'new', 'medium'),
  ('Tattoo Studio Paranoia', 'Tattoo', 'Avlabari', 'Revaz Tabukashvili St.', NULL, 'Maps', 'new', 'medium'),
  ('Black Swallow Tattoo', 'Tattoo', 'Avlabari', '29 Revaz Tabukashvili St.', NULL, 'Maps', 'new', 'medium'),
  ('Dola Tattoos', 'Tattoo', 'Nadzaladevi', '79 Rafael Agladze St.', NULL, 'Maps', 'new', 'medium'),
  ('Tattoo New Star', 'Tattoo', 'Mtatsminda', '43 Petre Melikishvili St.', NULL, 'Maps', 'new', 'medium'),
  ('Tago Tattoo', 'Tattoo', 'Saburtalo', '32 Petre Kavtaradze St.', NULL, 'Maps', 'new', 'medium'),
  ('Ashot Tattoo Studio', 'Tattoo', 'Saburtalo', '166/2 Otar Chiladze St.', NULL, 'Facebook', 'new', 'medium'),
  ('High Tattoo', 'Tattoo', 'Chugureti', '6 Mose Gogiberidze St.', NULL, 'Maps', 'new', 'medium'),
  ('Dope Ink Lab', 'Tattoo', 'Vake', '61 I. Abashidze St.', NULL, 'Facebook', 'new', 'medium'),
  ('Spartak Tattoo Studio', 'Tattoo', 'Avlabari', '25 Q. Tsamebuli St.', NULL, 'Maps', 'new', 'medium'),
  ('Compass Tattoo Shop', 'Tattoo', 'Didube', '16 Ipolite Khvichia St.', NULL, 'Maps', 'new', 'medium'),
  ('Sky Tattoo Studio', 'Tattoo', 'Mtatsminda', '40 Ivane Javakhishvili St.', NULL, 'Maps', 'new', 'medium'),
  ('Tattoo Studio Armstrong', 'Tattoo', 'Nadzaladevi', '8 Ia Kargareteli St.', NULL, 'Maps', 'new', 'medium'),
  ('Unlocked Tattoo Studio', 'Tattoo', 'Chugureti', '11/102 Zurab Chavchavadze St.', NULL, 'Maps', 'new', 'medium'),
  ('Penetro Piercing & Tattoo', 'Tattoo', 'Saburtalo', '18b Zhiuli Shartava St.', NULL, 'Maps', 'new', 'medium'),
  ('AUCH Piercing Studio', 'Piercing', 'Isani', '18 Napareuli St.', NULL, 'Instagram', 'new', 'medium'),
  ('Mardi Piercer', 'Piercing', 'Gldani', '30 Khizanishvili St.', '(511) 54 77 23', 'Maps', 'new', 'medium'),
  ('Desire Professional Piercing', 'Piercing', 'Chugureti', '53 Agmashenebeli Ave.', '(505) 55 65 13', 'Maps', 'new', 'medium'),
  ('Absolute Flex & Fitness', 'Gym', 'Nadzaladevi', 'Ts. Dadiani St. 26', '(555) 55 42 42', 'Facebook', 'new', 'medium'),
  ('Go Fitness', 'Gym', 'Sanzona', 'Guramishvili Ave. 15', '(577) 19 06 86', 'Facebook', 'new', 'medium'),
  ('Isani-Samgori Sports Center', 'Gym', 'Varketili', 'Rustaveli St. 3', '(599) 32 80 32', 'yell.ge', 'new', 'medium'),
  ('T & L Fitness Club', 'Gym', 'Nadzaladevi', 'Ts. Dadiani St. 105', '269 40 50', 'yell.ge', 'new', 'medium'),
  ('Fitness Time', 'Gym', 'Gldani', 'Khizanishvili St. 11', '215 88 00', 'yell.ge', 'new', 'medium'),
  ('Tonusi', 'Gym', 'Saburtalo', 'Kostavas St. 68', '218 02 15', 'yell.ge', 'new', 'medium'),
  ('Galileo Fitness', 'Gym', 'Gldani', 'Kerch St. 6d', '(551) 075 768', 'yell.ge', 'new', 'medium'),
  ('Natalia''s Fitness', 'Gym', 'Nadzaladevi', 'Ts. Dadiani St. 22/24', '(557) 77 22 50', 'yell.ge', 'new', 'medium'),
  ('Gagua Gym', 'Gym', 'Didi Digomi', 'Petre Iberi St. 6e', '(599) 52 97 98', 'Facebook', 'new', 'medium'),
  ('Old School Gym', 'Gym', 'Digomi', 'Digomi 6th Quarter 18', '(555) 10 20 80', 'yell.ge', 'new', 'medium'),
  ('Tidani', 'Gym', 'Saburtalo', 'Peking St. 9', '(593) 32 67 87', 'yell.ge', 'new', 'medium');

-- Batch 9: rows 401-450
INSERT INTO leads (name, category, district, address, phone, source, status, priority) VALUES
  ('Panorama Lisi Fitness', 'Gym', 'Lisi', 'Mukhran Machavariani St. 4', '(500) 90 20 20', 'yell.ge', 'new', 'medium'),
  ('Fit House', 'Gym', 'Samgori', 'Chichikinadze St. 2d', '(558) 78 24 54', 'yell.ge', 'new', 'medium'),
  ('Lion Fitness Pro', 'Gym', 'Digomi', 'Beliashvili St. 43', '222 88 55', 'yell.ge', 'new', 'medium'),
  ('Aversi Fitness', 'Gym', 'Saburtalo', 'Kazbegi Ave. 16', '2 500 700', 'yell.ge', 'new', 'medium'),
  ('Arena 1 Sports Complex', 'Gym', 'Saburtalo', 'University St. 2', '239 02 89', 'yell.ge', 'new', 'medium'),
  ('Start Fitness Club', 'Gym', 'Mukhiani', 'Mukhiani III district Corp. 10', '(558) 10 40 50', 'yell.ge', 'new', 'medium'),
  ('Aura Plus', 'Gym', 'Vake', 'Ir. Abashidze St. 28', '232 418', 'yell.ge', 'new', 'medium'),
  ('Bazeli', 'Gym', 'Saburtalo', 'Nutsubidze St. 161', '322 321 369', 'city24.ge', 'new', 'medium'),
  ('City Fitness', 'Gym', 'Saburtalo', 'N. Kipshidze St. 2', '322 200 444', 'city24.ge', 'new', 'medium'),
  ('Contours Express', 'Gym', 'Saburtalo', 'D. Gamrekeli St. 10-12', '322 727 000', 'city24.ge', 'new', 'medium'),
  ('Curves', 'Gym', 'Nadzaladevi', 'Mtskheta St. 17', '322 432 200', 'city24.ge', 'new', 'medium'),
  ('Digomi Gym', 'Gym', 'Digomi', 'A. Beliashvili St. 5', '322 515 094', 'city24.ge', 'new', 'medium'),
  ('Dilato Fitness Club', 'Gym', 'Saburtalo', 'Pekin Ave. 5', '322 365 676', 'city24.ge', 'new', 'medium'),
  ('Elite Fitness', 'Gym', 'Vera', 'N. Nikoladze St. 7', '322 999 543', 'city24.ge', 'new', 'medium'),
  ('Figura', 'Gym', 'Didube', 'I. Kereselidze St. 36', '571 102 020', 'city24.ge', 'new', 'medium'),
  ('Fitness Club Aphrodite', 'Gym', 'Saburtalo', 'Pekin Ave. 2', '555 903 200', 'city24.ge', 'new', 'medium'),
  ('Galatea', 'Gym', 'Saburtalo', 'Pekin Ave. 33', '322 253 752', 'city24.ge', 'new', 'medium'),
  ('La Belle Sport', 'Gym', 'Sololaki', 'Galaktioni St. 3-5', '593 314 145', 'city24.ge', 'new', 'medium'),
  ('Marilyn Fitness', 'Gym', 'Saburtalo', 'Nutsubidze St. 62', '322 142 451', 'city24.ge', 'new', 'medium'),
  ('New York Prolife Fitness & Spa', 'Gym', 'Saburtalo', 'Pekin Ave. 41', '322 297 0207', 'city24.ge', 'new', 'medium'),
  ('Urban Gurus', 'Gym', 'Saburtalo', 'P. Ioseliani St. 12', '579 209 994', 'city24.ge', 'new', 'medium'),
  ('Matrix Fitness', 'Gym', 'Sanzona / Isani', 'Guramishvili Ave. 63 / Bolnisi St. 46', '(579) 22 26 08', 'Facebook', 'new', 'medium'),
  ('Sparta Fitness', 'Gym', 'Digomi', 'Ljubljana St.', '(598) 55 56 70', 'Facebook', 'new', 'medium'),
  ('Fit Gallery', 'Gym', 'Vake', 'I. Chavchavadze Ave. 11a', NULL, 'Facebook', 'new', 'medium'),
  ('Fit Line Sport', 'Gym', 'Saburtalo', 'Sulkhan Tsintsadze St. 39', NULL, 'Facebook', 'new', 'medium'),
  ('FitLand', 'Gym', 'Saburtalo', 'Peking St. 5', '(505) 55 82 48', 'yell.ge', 'new', 'medium'),
  ('Tanadi Fitness', 'Gym', 'Saburtalo', 'Ioseliani St. 12/14', '(599) 38 82 77', 'yell.ge', 'new', 'medium'),
  ('Sport Time', 'Gym', 'Ortachala', 'Gorgasali St. 75a', '272 21 44', 'yell.ge', 'new', 'medium'),
  ('Leila Meskhi Sports Complex', 'Gym', 'Chugureti', 'Marjanishvili St. 29g', '295 38 00', 'yell.ge', 'new', 'medium'),
  ('Fitness House', 'Gym', 'Varketili', '17 Nazi Shamanauri St.', '(557) 06 33 66', 'yell.ge', 'new', 'medium'),
  ('DL Fitness', 'Gym', 'Samgori', 'Kindzmarauli Lane 4b', '(598) 19 97 06', 'yell.ge', 'new', 'medium'),
  ('Shio Sports Performance', 'Gym', 'Didube', 'Tsereteli Ave. 105a', '(555) 68 22 31', 'yell.ge', 'new', 'medium'),
  ('Move Club', 'Gym', 'Nadzaladevi', 'Chkondideli St. 4', '(597) 29 99 92', 'yell.ge', 'new', 'medium'),
  ('Pro Fitness 3', 'Gym', 'Vazisubani', 'Osip Mandelstam St. 6', '(598) 27 14 15', 'yell.ge', 'new', 'medium'),
  ('Yoga Studio 9', 'Yoga', 'Saburtalo', 'Zhuli Shartava St. 41', NULL, 'Facebook', 'new', 'medium'),
  ('El Pilates Studio', 'Pilates', 'Tbilisi', NULL, NULL, 'Instagram', 'new', 'medium'),
  ('Reformer Pilates Private Studio', 'Pilates', 'Saburtalo', 'Sulkhan Tsintsadze St. 5', '597 004 145', 'Facebook', 'new', 'medium'),
  ('Fit Club at The Art House', 'Gym', 'Sololaki', 'Lado Gudiashvili St. 18', '544 44 40 03', 'Facebook', 'new', 'medium'),
  ('POM POM Bakery', 'Bakery', 'Saburtalo', '54 Vazha-Pshavela Ave.', '(598) 87 70 00', 'yell.ge', 'new', 'medium'),
  ('Bakery SAAMO', 'Bakery', 'Sanzona', '2 Gudamakari St.', '(597) 40 72 72', 'yell.ge', 'new', 'medium'),
  ('Antre Batono', 'Bakery', 'Avlabari', '52/55 Tsurtsumia St.', '(574) 40 41 07', 'yell.ge', 'new', 'medium'),
  ('Artizani Bakery', 'Bakery', 'Saburtalo', '8 Tsintsadze St.', '(568) 68 86 09', 'yell.ge', 'new', 'medium'),
  ('Ipkli Digomi', 'Bakery', 'Digomi', 'Chaladze St.', '(598) 88 55 08', 'yell.ge', 'new', 'medium'),
  ('BreadBar', 'Bakery', 'Vake', '2b Kipshidze St.', '(577) 43 00 00', 'yell.ge', 'new', 'medium'),
  ('Osuri Khachapuri House Champion', 'Bakery', 'Gldani', '46a Tianeti Highway', '(599) 74 43 43', 'yell.ge', 'new', 'medium'),
  ('Firini', 'Bakery', 'Saburtalo', '41 Vazha-Pshavela Ave.', '(558) 18 04 05', 'yell.ge', 'new', 'medium'),
  ('Mtabarshi', 'Bakery', 'Vake', '9b Kipshidze St.', '(593) 946 986', 'yell.ge', 'new', 'medium'),
  ('Sazano Bakery', 'Bakery', 'Saburtalo', '43 Peking St.', '(599) 61 44 31', 'yell.ge', 'new', 'medium'),
  ('Ana+ Bakery', 'Bakery', 'Didi Digomi', '18 G. Brtskinvale St.', '(555) 11 03 15', 'yell.ge', 'new', 'medium'),
  ('Zafrana Bakery', 'Bakery', 'Isani', '41a Beri Gabriel Salosi Ave.', '(596) 76 10 00', 'yell.ge', 'new', 'medium');

-- Batch 10: rows 451-500
INSERT INTO leads (name, category, district, address, phone, source, status, priority) VALUES
  ('Boulangerie Breton', 'Bakery', 'Vake', '49e Chavchavadze Ave.', '(595) 66 62 62', 'yell.ge', 'new', 'medium'),
  ('Paul Bakery', 'Bakery', 'Vake', '26 I. Abashidze St.', '(551) 93 77 99', 'yell.ge', 'new', 'medium'),
  ('Lagazi Bakery', 'Bakery', 'Avlabari', '8a Tsinandali St.', '(551) 55 52 07', 'yell.ge', 'new', 'medium'),
  ('Georgian Bread House', 'Bakery', 'Saburtalo', '2 O. Chkheidze St.', '(551) 32 77 66', 'yell.ge', 'new', 'medium'),
  ('Puri Guliani', 'Bakery', 'Chugureti', 'Saarbrucken Sq.', '(577) 00 00 83', 'yell.ge', 'new', 'medium'),
  ('Kartuli Gemo', 'Bakery', 'Digomi', 'Digomi Massive Q.2 B.7a', '(558) 80 44 44', 'yell.ge', 'new', 'medium'),
  ('Bakerline', 'Bakery', 'Saburtalo', '78a Vazha-Pshavela Ave.', '(599) 578 776', 'yell.ge', 'new', 'medium'),
  ('Rachuli Lobiani', 'Bakery', 'Saburtalo', '37 Kazbegi Ave.', '(551) 65 09 00', 'yell.ge', 'new', 'medium'),
  ('Cafe Kombinati', 'Bakery', 'Mtatsminda', '2 Mtkvari St.', '(577) 12 78 18', 'yell.ge', 'new', 'medium'),
  ('Tavtavi Bread Factory', 'Bakery', 'Gldani', 'Mosulisvili St. 1', '(571) 40 80 19', 'yell.ge', 'new', 'medium'),
  ('Marshe Bread', 'Bakery', 'Didube', 'T. Eristavi Lane 9', '224 23 00', 'yell.ge', 'new', 'medium'),
  ('Khvastagi Bread', 'Bakery', 'Nadzaladevi', 'Ts. Dadiani St. 18/34', '(551) 25 55 55', 'yell.ge', 'new', 'medium'),
  ('FBD Bread', 'Bakery', 'Varketili', 'Plot 14/430', '(591) 91 85 41', 'yell.ge', 'new', 'medium'),
  ('Kevri 2017', 'Bakery', 'Saburtalo (Nutsubidze)', 'Nutsubidze Plateau', '(579) 34 33 61', 'yell.ge', 'new', 'medium'),
  ('Kamaria Bakery', 'Bakery', 'Vake', 'Paliashvili St. 59', '(593) 11 44 78', 'yell.ge', 'new', 'medium'),
  ('Giorgi-94 Bread', 'Bakery', 'Isani', 'Meveles St. 3', '270 82 26', 'yell.ge', 'new', 'medium'),
  ('Puri Chveni Arsobisa', 'Bakery', 'Nadzaladevi', 'Kldekar St. 23', '224 60 67', 'yell.ge', 'new', 'medium'),
  ('Swiss Baker', 'Bakery', 'Saburtalo (Nutsubidze)', 'Plateau IV', '(599) 45 22 32', 'yell.ge', 'new', 'medium'),
  ('Vasadze''s Bread', 'Bakery', 'Ponichala', 'Rustavi Highway', '283 88 88', 'yell.ge', 'new', 'medium'),
  ('Mamapapuri', 'Bakery', 'Saburtalo', 'Vazha-Pshavela Ave.', '(557) 70 19 81', 'yell.ge', 'new', 'medium'),
  ('Natela''s Bread', 'Bakery', 'Didube', 'Gvetadze St. 6', '(599) 35 18 18', 'yell.ge', 'new', 'medium'),
  ('Pane Bread', 'Bakery', 'Avchala', 'David Sarajishvili Ave. 4', '265 04 14', 'yell.ge', 'new', 'medium'),
  ('Kipiani''s Bread', 'Bakery', 'Vake', 'Shroshi St. 1', '(599) 30 64 46', 'yell.ge', 'new', 'medium'),
  ('Pagari', 'Bakery', 'Saburtalo', 'Beijing St. 34', '(568) 43 42 70', 'yell.ge', 'new', 'medium'),
  ('Bebo''s Lavashi', 'Bakery', 'Elia', 'Dominika Eristavi St. 28', '(514) 03 00 03', 'yell.ge', 'new', 'medium'),
  ('Margi Bakery', 'Bakery', 'Saburtalo (Nutsubidze)', 'R. Chkhikvadze St. 6', '(599) 93 31 32', 'yell.ge', 'new', 'medium'),
  ('Narekatsi Bread', 'Bakery', 'Isani', 'Abuseridze-Tbeli St. 23', '270 02 70', 'yell.ge', 'new', 'medium'),
  ('Praline Confectionery', 'Confectionery', 'Vera', '2 Tarkhnishvili St.', '(599) 736 736', 'yell.ge', 'new', 'medium'),
  ('Sugar Free', 'Confectionery', 'Saburtalo', '30 Kazbegi Ave.', '(599) 77 93 93', 'yell.ge', 'new', 'medium'),
  ('Dzidza''s Cakes', 'Confectionery', 'Vake', '9 Mosashvili St.', '(577) 90 74 74', 'yell.ge', 'new', 'medium'),
  ('Nile Confectionery', 'Confectionery', 'Digomi', 'Digomi Massive Q. 4 B. 5a', '(558) 00 00 32', 'yell.ge', 'new', 'medium'),
  ('Cake Cafe', 'Confectionery', 'Vake', '22 I. Abashidze St.', '223 12 92', 'yell.ge', 'new', 'medium'),
  ('Lalas Time', 'Confectionery', 'Varketili', '89 Gakhokidze St.', '(555) 81 77 55', 'yell.ge', 'new', 'medium'),
  ('Lampone', 'Confectionery', 'Saburtalo', '77 Tsintsadze St.', '(595) 16 00 17', 'yell.ge', 'new', 'medium'),
  ('Tanias Cakes', 'Confectionery', 'Sololaki', '6/3 Kikodze St.', '293 42 88', 'yell.ge', 'new', 'medium'),
  ('Recepti Confectionery', 'Confectionery', 'Didube', '48 Tsereteli Ave.', '(557) 305 305', 'yell.ge', 'new', 'medium'),
  ('European Confectionery Lika', 'Confectionery', 'Nadzaladevi', '253 Ts. Dadiani St.', '(591) 450 470', 'yell.ge', 'new', 'medium'),
  ('Tartalia', 'Confectionery', 'Didube', '18 Evdoshvili St.', '(514) 74 77 47', 'yell.ge', 'new', 'medium'),
  ('Belinsky Cake', 'Confectionery', 'Saburtalo', '16 S. Chikovani St.', '(599) 01 21 22', 'yell.ge', 'new', 'medium'),
  ('Pie Confectionery', 'Confectionery', 'Saburtalo', '11 Dolidze St.', '(599) 42 45 15', 'yell.ge', 'new', 'medium'),
  ('Cake Lab', 'Confectionery', 'Didi Digomi', '13 I. Petritsi St.', '256 01 52', 'yell.ge', 'new', 'medium'),
  ('Amarena', 'Confectionery', 'Gldani', '53 A. Bochorishvili St.', '(579) 77 77 88', 'yell.ge', 'new', 'medium'),
  ('Perogico', 'Confectionery', 'Vake', '3 Levan Mikeladze St.', '(568) 82 75 45', 'yell.ge', 'new', 'medium'),
  ('Marron Pastry', 'Confectionery', 'Digomi', '6 M. Gogiberidze St.', '(558) 04 88 44', 'yell.ge', 'new', 'medium'),
  ('Tartan Cafeteria', 'Confectionery', 'Vera', '17 Tatishvili St.', '(568) 16 77 16', 'yell.ge', 'new', 'medium'),
  ('Restaurant Bagebey', 'Restaurant', 'Vake (Bagebi)', '10 Tskneti Highway', '(599) 90 14 14', 'yell.ge', 'new', 'medium'),
  ('Antsi Restaurant', 'Restaurant', 'Saburtalo', 'Zh. Shartava St. 44', '322907701', 'city24.ge', 'new', 'medium'),
  ('Assa Holi', 'Restaurant', 'Mtatsminda', 'Rkinis Rigi 6', '577 98 58 58', 'city24.ge', 'new', 'medium'),
  ('Aphkhazethi Restaurant', 'Restaurant', 'Mtatsminda', 'Sanapiros St. 2', '322249249', 'city24.ge', 'new', 'medium'),
  ('Aphkhazura Restaurant', 'Restaurant', 'Saburtalo', 'Qsnis St. 14', '322370152', 'city24.ge', 'new', 'medium');

-- Batch 11: rows 501-550
INSERT INTO leads (name, category, district, address, phone, source, status, priority) VALUES
  ('Atinati Restaurant', 'Restaurant', 'Chugureti', 'D. Agmashenebeli Ave. 73', '322982346', 'city24.ge', 'new', 'medium'),
  ('Ali Baba Sopra', 'Restaurant', 'Isani', 'D. Agmashenebeli Ave. 116', '322181844', 'city24.ge', 'new', 'medium'),
  ('Aktrisa Margarita', 'Restaurant', 'Saburtalo', 'S. Eulis St. 7', '599024030', 'city24.ge', 'new', 'medium'),
  ('Sofiko Restaurant', 'Restaurant', 'Saburtalo', 'Zdanevichi Brothers St. 8', NULL, 'madloba.info', 'new', 'medium'),
  ('Restaurant Chveni', 'Restaurant', 'Saburtalo', 'Anzor Erkomaishvili St. 8b', NULL, 'madloba.info', 'new', 'medium'),
  ('Muse Restaurant', 'Restaurant', 'Saburtalo', 'Vertskhli St. 52', NULL, 'madloba.info', 'new', 'medium'),
  ('Akustik Bari', 'Cafe/Bar', 'Saburtalo', 'A. Mitskevichis St. 6', '597381124', 'city24.ge', 'new', 'medium'),
  ('Alkohol Bari', 'Cafe/Bar', 'Vake', 'Ir. Abashidze St. 41', '322290723', 'city24.ge', 'new', 'medium'),
  ('Ankara Cafe', 'Cafe/Bar', 'Isani', 'D. Agmashenebeli Ave. 128', '322957281', 'city24.ge', 'new', 'medium'),
  ('Antre Cafe', 'Cafe/Bar', 'Saburtalo', 'V. Petriashvili St. 19', '595338213', 'city24.ge', 'new', 'medium'),
  ('A-Petiti', 'Cafe/Bar', 'Saburtalo', 'Peking Ave. 5', '3223212871', 'city24.ge', 'new', 'medium'),
  ('Art Boksi', 'Cafe/Bar', 'Mtatsminda', 'Griboedovis St. 21', '322920039', 'city24.ge', 'new', 'medium'),
  ('Art Cafe', 'Cafe/Bar', 'Nadzaladevi', 'Sh. Dadianis St. 9', '322920280', 'city24.ge', 'new', 'medium'),
  ('Aspendosi', 'Cafe/Bar', 'Vake', 'Kekelidze St. 2', '322235835', 'city24.ge', 'new', 'medium'),
  ('Azteka Bar', 'Cafe/Bar', 'Vake', 'Ir. Abashidze St. 43', '322226018', 'city24.ge', 'new', 'medium'),
  ('Bada-Bumi', 'Cafe/Bar', 'Vake', 'Z. Paliashvili St. 72', '322291626', 'city24.ge', 'new', 'medium'),
  ('Bar 404', 'Cafe/Bar', 'Saburtalo', 'Vashlovanis St. 5', '592447777', 'city24.ge', 'new', 'medium'),
  ('Bar Nova', 'Cafe/Bar', 'Vake', 'Ir. Abashidze St. 27', '322250165', 'city24.ge', 'new', 'medium'),
  ('Batonebi', 'Cafe/Bar', 'Vake', 'Z. Paliashvili St. 64', '32250669', 'city24.ge', 'new', 'medium'),
  ('Belvili', 'Cafe/Bar', 'Mtatsminda', 'L. Qiachellis St. 26', '322936553', 'city24.ge', 'new', 'medium'),
  ('Ben Chelero', 'Cafe/Bar', 'Mtatsminda', 'Mtkvris St. 6', '322999003', 'city24.ge', 'new', 'medium'),
  ('Cafe Daphna', 'Cafe/Bar', 'Mtatsminda', 'Atoneli St. 29', NULL, 'city24.ge', 'new', 'medium'),
  ('Premium Auto', 'Auto Repair', 'Gldani', '48 I. Vekua St.', '(599) 518 815', 'yell.ge', 'new', 'medium'),
  ('Iardi Auto', 'Auto Repair', 'Samgori', '29 Zurab Iarajuli St.', '224 20 24', 'yell.ge', 'new', 'medium'),
  ('Isani-92', 'Auto Repair', 'Samgori', '29a Moscow Ave.', '270 05 05, (571) 05 05 65', 'yell.ge', 'new', 'medium'),
  ('Eco Hybrid', 'Auto Repair', 'Digomi', '63 Beliashvili St.', '(599) 07 90 09', 'yell.ge', 'new', 'medium'),
  ('Prime Motors', 'Auto Repair', 'Digomi', '15 A. Bakradze St.', '(577) 61 15 15', 'yell.ge', 'new', 'medium'),
  ('Euro Motor', 'Auto Repair', 'Zahesi', '5 Kazbegi St.', '(557) 78 11 77', 'yell.ge', 'new', 'medium'),
  ('Irdagi', 'Auto Repair', 'Samgori', '4 Samgori St.', '(598) 86 20 22', 'yell.ge', 'new', 'medium'),
  ('Auto Zone', 'Auto Repair', 'Digomi', '19 Tereverko St.', '(571) 00 00 11', 'yell.ge', 'new', 'medium'),
  ('Inter-Service', 'Auto Repair', 'Didube', '23 Vakhushti Bagrationi St.', '235 50 28', 'yell.ge', 'new', 'medium'),
  ('Airbags Repair', 'Auto Repair', 'Didube', '29 Khosharauli St.', '(598) 55 61 61', 'yell.ge', 'new', 'medium'),
  ('Chevrolet Centre', 'Auto Repair', 'Digomi', '123 Beliashvili St.', '(591) 15 48 49', 'yell.ge', 'new', 'medium'),
  ('City Garage', 'Auto Repair', 'Digomi', '25 Levan Rcheulishvili St.', '(599) 89 03 03', 'yell.ge', 'new', 'medium'),
  ('Auto Workshop', 'Auto Repair', 'Didi Digomi', '109 Mirian Mepe St.', '(593) 03 99 33', 'yell.ge', 'new', 'medium'),
  ('F Service', 'Auto Repair', 'Didi Digomi', '36 Rostevani St.', '(577) 00 74 36', 'yell.ge', 'new', 'medium'),
  ('Amboli Auto', 'Auto Repair', 'Didube', 'A. Tsereteli Ave. 41', '790 12 10 04', 'city24.ge', 'new', 'medium'),
  ('Autoservice (Kavtaradze)', 'Auto Repair', 'Saburtalo', 'P. Kavtaradze St. 16', '599 50 08 50', 'city24.ge', 'new', 'medium'),
  ('Carport', 'Auto Repair', 'Saburtalo', 'Nutsubidze St. 41', '322 31 13 41', 'city24.ge', 'new', 'medium'),
  ('Center Motors', 'Auto Repair', 'Saburtalo', 'P. Kavtaradze St. 5', '599 55 43 45', 'city24.ge', 'new', 'medium'),
  ('Gas-German Auto Service', 'Auto Repair', 'Didube', 'T. Eristavi St. 6', '322 69 50 50', 'city24.ge', 'new', 'medium'),
  ('General Service', 'Auto Repair', 'Nadzaladevi', 'R. Agladze St. 39', '322 35 58 88', 'city24.ge', 'new', 'medium'),
  ('GTM Auto Service', 'Auto Repair', 'Isani', 'Maisuradze St. 11', '574 86 77 11', 'city24.ge', 'new', 'medium'),
  ('IRR Group', 'Auto Repair', 'Sanzona', 'D. Guramishvili Ave. 39a', '574 44 87 78', 'city24.ge', 'new', 'medium'),
  ('Shukura Auto Service', 'Auto Repair', 'Mtatsminda', 'Sheshelidze St. 7', '557 64 65 68', 'city24.ge', 'new', 'medium'),
  ('Volti Auto', 'Auto Repair', 'Didube', 'Khosharauli St. 30', '551 06 11 99', 'city24.ge', 'new', 'medium'),
  ('Yamato', 'Auto Repair', 'Chugureti', 'Marijani St. 2a', '322 30 83 08', 'city24.ge', 'new', 'medium'),
  ('Global Inspection Company', 'Auto Repair', 'Gldani', '28 Levan Kbilashvili St.', '(555) 00 00 35', 'yell.ge', 'new', 'medium'),
  ('My Autoservice', 'Auto Repair', 'Avlabari', '64 Telavi St.', '(557) 50 16 06', 'yell.ge', 'new', 'medium'),
  ('Key Programming Auto Diagnostic', 'Auto Repair', 'Avlabari', 'Near Rike', '599 91 00 81', 'yell.ge', 'new', 'medium');

-- Batch 12: rows 551-600
INSERT INTO leads (name, category, district, address, phone, source, status, priority) VALUES
  ('Cezarioni', 'Auto Repair', 'Sanzona', 'Guramishvili Ave. & Gudamakari', '(558) 11 77 96', 'yell.ge', 'new', 'medium'),
  ('Best Car Diagnostic', 'Auto Repair', 'Vazisubani', 'I M/D B. 4', '(568) 94 34 27', 'yell.ge', 'new', 'medium'),
  ('Test Diagnostic', 'Auto Repair', 'Digomi', '119b Agmashenebeli Alley', '(551) 32 20 06', 'yell.ge', 'new', 'medium'),
  ('Mix Car Paint', 'Auto Repair', 'Saburtalo', 'P. Kavtaradze St. 24', '551 32 34 34', 'city24.ge', 'new', 'medium'),
  ('AB-VET (Buneba)', 'Veterinary', 'Saburtalo', '166/5 O. Chiladze St.', '238 98 11, (593) 55 79 79', 'yell.ge', 'new', 'medium'),
  ('Paata Chkheidze Vet Clinic VETI', 'Veterinary', 'Didube', '12a Stanislavski St.', '(577) 47 62 97', 'yell.ge', 'new', 'medium'),
  ('Be Wild Vet', 'Veterinary', 'Didube', '27a Batumi St.', '(555) 27 26 33', 'yell.ge', 'new', 'medium'),
  ('Balto Vet', 'Veterinary', 'Saburtalo', '20a Kazbegi Ave.', '256 05 07, (595) 61 77 33', 'yell.ge', 'new', 'medium'),
  ('Zoo Life', 'Veterinary', 'Vera', '19 Kostava St.', '(593) 733 973', 'yell.ge', 'new', 'medium'),
  ('Natia Beridze & Co Vet', 'Veterinary', 'Saburtalo (Nutsubidze)', '64 Nutsubidze St.', '232 54 08', 'yell.ge', 'new', 'medium'),
  ('Zooplaza Vet (Digomi)', 'Veterinary', 'Digomi', 'Q. 3 Paichadze St.', '(598) 59 93 01', 'yell.ge', 'new', 'medium'),
  ('Vet Health', 'Veterinary', 'Gldani', '41 Khizanishvili St.', '(555) 51 00 08', 'yell.ge', 'new', 'medium'),
  ('Lucky Paw', 'Veterinary', 'Saburtalo', '44 Kavtaradze St.', '(551) 00 55 81', 'yell.ge', 'new', 'medium'),
  ('Animals Market', 'Veterinary', 'Digomi', '43 Beliashvili St.', '(592) 430 430', 'yell.ge', 'new', 'medium'),
  ('VetLife', 'Veterinary', 'Saburtalo (Vedzisi)', '41 Kandelaki St.', '230 50 59', 'yell.ge', 'new', 'medium'),
  ('Pets Care Vet', 'Veterinary', 'Ortachala', '28 Gorgasali St.', '591 68 46 88', 'yell.ge', 'new', 'medium'),
  ('Vet Point', 'Veterinary', 'Vera', '8 Shanidze St.', '223 22 67, (555) 73 62 62', 'yell.ge', 'new', 'medium'),
  ('Companion Vet', 'Veterinary', 'Chugureti', '86 Tsinamdzgvrishvili St.', '295 85 77', 'yell.ge', 'new', 'medium'),
  ('Zoobum', 'Veterinary', 'Ortachala', '14 Krtsanisi St.', '(577) 99 66 20', 'yell.ge', 'new', 'medium'),
  ('Beethoven Pet & Vet', 'Veterinary', 'Isani', '22 Sh. Nadirashvili St.', '(592) 00 99 43', 'yell.ge', 'new', 'medium'),
  ('Zoo Family', 'Veterinary', 'Chugureti', '2 Dgebuadze St.', '(595) 55 48 66', 'yell.ge', 'new', 'medium'),
  ('Veterinary Consulting-Room', 'Veterinary', 'Samgori', '3 Moscow Ave.', '(557) 96 05 20', 'yell.ge', 'new', 'medium'),
  ('Zooland', 'Pet Shop', 'Didi Digomi', '5 I. Petritsi St.', '(555) 27 26 33', 'yell.ge', 'new', 'medium'),
  ('Zaravet', 'Veterinary', 'Saburtalo', '77 Tsintsadze St.', '(599) 99 64 87', 'yell.ge', 'new', 'medium'),
  ('Leader Vet', 'Veterinary', 'Chugureti', '57 Chikobava St.', '(579) 99 82 82', 'yell.ge', 'new', 'medium'),
  ('Vet-Express', 'Veterinary', 'Gldani', 'Vekua St. 77', '599 51 55 97', 'vetnet.ge', 'new', 'medium'),
  ('Brolia Vet', 'Veterinary', 'Sanzona', 'Guramishvili Ave. 56b', '599 61 79 00', 'vetnet.ge', 'new', 'medium'),
  ('New Vet', 'Veterinary', 'Saburtalo', 'Khomlelis St. 4a', '032 2 76 33 86', 'vetnet.ge', 'new', 'medium'),
  ('Vetex', 'Veterinary', 'Saburtalo', 'Politkovskaya St. 50', '597 12 73 12', 'vetnet.ge', 'new', 'medium'),
  ('Zoocity', 'Pet Shop', 'Saburtalo', 'Kazbegi Ave. 51', '591 04 23 41', 'vetnet.ge', 'new', 'medium'),
  ('Vet-Art', 'Veterinary', 'Didi Digomi', 'G. Brtskinvale St. 33', '555 63 17 87', 'vetnet.ge', 'new', 'medium'),
  ('Aibo Vet', 'Veterinary', 'Saburtalo', 'Tsintsadze St. 45', '032 2 91 12 53', 'vetnet.ge', 'new', 'medium'),
  ('Medoni Vet', 'Veterinary', 'Digomi', 'Agmashenebeli Alley', '599 91 73 32', 'vetnet.ge', 'new', 'medium'),
  ('Tati Pet Shop', 'Pet Shop', 'Nadzaladevi', '313 Ts. Dadiani St.', '(593) 64 94 45', 'yell.ge', 'new', 'medium'),
  ('Pet House', 'Pet Shop', 'Didi Digomi', '11 I. Petritsi St.', '(558) 20 44 27', 'yell.ge', 'new', 'medium'),
  ('Muria Pet Shop', 'Pet Shop', 'Saburtalo', '36 Peking St.', NULL, 'yell.ge', 'new', 'medium'),
  ('Berule Pet Shop', 'Pet Shop', 'Isani', '73 St. Queen Ketevan Ave.', '274 88 04', 'yell.ge', 'new', 'medium'),
  ('Zooplaza Pet Shop', 'Pet Shop', 'Saburtalo', '67 Kostava St.', '236 54 14', 'yell.ge', 'new', 'medium'),
  ('Zooarea', 'Pet Shop', 'Nadzaladevi', '133a Ts. Dadiani St.', '(591) 90 50 50', 'yell.ge', 'new', 'medium'),
  ('Pets Choice', 'Pet Shop', 'Saburtalo', '61 Iosebidze St.', '(597) 77 79 44', 'yell.ge', 'new', 'medium'),
  ('Zoomax', 'Pet Shop', 'Vera', '17 Kostava St.', '292 03 27', 'yell.ge', 'new', 'medium'),
  ('Zoohub', 'Pet Shop', 'Saburtalo', '18 Bakhtrioni St.', '032 218 55 56', 'yell.ge', 'new', 'medium'),
  ('Animal Planet Pet', 'Pet Shop', 'Varketili', '74 Kupradze St. b. 6', '(511) 22 16 01', 'yell.ge', 'new', 'medium'),
  ('Urban Tales Pet', 'Pet Shop', 'Vera', '84 Barnovi St.', '280 00 89', 'yell.ge', 'new', 'medium'),
  ('Pet Spot', 'Pet Shop', 'Saburtalo (Vedzisi)', '4i Panjikidze St.', '(555) 16 22 55', 'yell.ge', 'new', 'medium'),
  ('Bongo Zoo Centre (grooming)', 'Pet Grooming', 'Ortachala', '28 Gorgasali St.', '(591) 684 688', 'yell.ge', 'new', 'medium'),
  ('At Pudas (grooming)', 'Pet Grooming', 'Saburtalo', '67 Kostava St.', '(557) 46 70 02', 'yell.ge', 'new', 'medium'),
  ('Clean Paws', 'Pet Grooming', 'Saburtalo', '3 Politkovskaya St. b. 32', '(555) 000 363', 'yell.ge', 'new', 'medium'),
  ('Groom-Groom', 'Pet Grooming', 'Saburtalo (Nutsubidze)', '82 Nutsubidze St.', '(577) 22 30 33', 'yell.ge', 'new', 'medium'),
  ('BarberPet Grooming', 'Pet Grooming', 'Vake', '32 Paliashvili St.', '(544) 44 60 00', 'yell.ge', 'new', 'medium');

-- Batch 13: rows 601-650
INSERT INTO leads (name, category, district, address, phone, source, status, priority) VALUES
  ('Babis Grooming', 'Pet Grooming', 'Vera', '86 Barnovi St.', '(599) 45 33 04', 'yell.ge', 'new', 'medium'),
  ('Chaplin Photo Studio', 'Photography', 'Saburtalo', '24 Kazbegi Ave. R. 15', '(577) 54 68 88', 'yell.ge', 'new', 'medium'),
  ('VF Studio', 'Photography', 'Tbilisi', NULL, '(599) 90 52 80', 'yell.ge', 'new', 'medium'),
  ('AirVision', 'Photography', 'Saburtalo', '3a Dzotsenidze St.', '(598) 51 66 00', 'yell.ge', 'new', 'medium'),
  ('Odelia Studio', 'Photography', 'Digomi', 'Robakidze Ave.', '(593) 21 16 56', 'yell.ge', 'new', 'medium'),
  ('MGI Studio', 'Photography', 'Saburtalo', '53 Kazbegi Ave.', '(577) 17 99 66', 'yell.ge', 'new', 'medium'),
  ('G Studia Photo-Video', 'Photography', 'Chugureti', '2 Uznadze St.', '(579) 35 00 34', 'yell.ge', 'new', 'medium'),
  ('Panorama Studio Georgia', 'Photography', 'Isani', '6d Gia Bakarashvili St.', '(595) 55 24 24', 'yell.ge', 'new', 'medium'),
  ('Photosalon Pixel', 'Photography', 'Varketili', '24 Sukhishvili St.', '(599) 88 70 05', 'yell.ge', 'new', 'medium'),
  ('Panda Photo Print Shop', 'Photography', 'Saburtalo', '2 Tsintsadze St.', '(555) 33 76 71', 'yell.ge', 'new', 'medium'),
  ('Fotograf', 'Photography', 'Avlabari', '5 Tsinandali St.', '(555) 94 20 05', 'yell.ge', 'new', 'medium'),
  ('Jeo Di Art Studio', 'Photography', 'Didi Digomi', 'near 19 I. Petritsi St.', '(551) 45 42 44', 'yell.ge', 'new', 'medium'),
  ('B & W Gallery', 'Photography', 'Vera', '46b Gogebashvili St.', '243 00 57', 'yell.ge', 'new', 'medium'),
  ('Prime Photo Studio', 'Photography', 'Vera', '26 Kostava St.', '(557) 15 95 10', 'yell.ge', 'new', 'medium'),
  ('Express Photo', 'Photography', 'Vake', '22 Chavchavadze Ave.', '(571) 22 46 13', 'yell.ge', 'new', 'medium'),
  ('Zoom Room', 'Photography', 'Vake', '52 I. Chavchavadze Ave.', '599 11 18 09', 'city24.ge', 'new', 'medium'),
  ('Zoom Studio', 'Photography', 'Mtatsminda', '36 Rustaveli Ave.', '595 59 20 60', 'city24.ge', 'new', 'medium'),
  ('Boke Photo', 'Photography', 'Saburtalo', '8 Al. Kazbegi Ave.', '599 53 58 53', 'city24.ge', 'new', 'medium'),
  ('Konica Digital Studio', 'Photography', 'Isani', '58 Ketevani Tsamebuli Ave.', '322 77 62 43', 'city24.ge', 'new', 'medium'),
  ('Photo World', 'Photography', 'Chugureti', '86-90 D. Agmashenebeli Ave.', '322 91 07 31', 'city24.ge', 'new', 'medium'),
  ('Accounting Training Center', 'Education', 'Didube', '95 Tsereteli Ave.', '(593) 11 39 19', 'yell.ge', 'new', 'medium'),
  ('Educational Centre Ravi', 'Education', 'Avlabari', '14 Dusheti St.', '(595) 13 82 38', 'yell.ge', 'new', 'medium'),
  ('Learning Centre Lampari', 'Education', 'Chugureti', '108 Agmashenebeli Ave.', '(599) 38 50 10', 'yell.ge', 'new', 'medium'),
  ('Free Academy', 'Education', 'Saburtalo', '47 Kazbegi Ave.', '(598) 99 45 51', 'yell.ge', 'new', 'medium'),
  ('Training Centre Garanty', 'Education', 'Tbilisi', NULL, '(597) 10 86 37', 'yell.ge', 'new', 'medium'),
  ('Education Center (Isani)', 'Education', 'Isani', '70 Atskuri St.', '(571) 20 44 65', 'yell.ge', 'new', 'medium'),
  ('BLC Teaching Center', 'Education', 'Mtatsminda', '38 Vertskhli St.', '(577) 36 80 48', 'yell.ge', 'new', 'medium'),
  ('John Corlett Language Centre', 'Education', 'Saburtalo', '5 Mitskevich St.', '238 38 64', 'yell.ge', 'new', 'medium'),
  ('China International Education', 'Education', 'Saburtalo', '43 Balanchivadze St.', '(551) 68 66 88', 'yell.ge', 'new', 'medium'),
  ('Professional 2010', 'Education', 'Vera', '45 Kostava St.', '(555) 63 48 01', 'yell.ge', 'new', 'medium'),
  ('Lider Group Training', 'Education', 'Varketili', '15 Lisa Nakashidze-Bolkvadze St.', '(555) 19 83 69', 'yell.ge', 'new', 'medium'),
  ('Sophix Education', 'Education', 'Vake', '10 Paliashvili St.', '(571) 10 71 01', 'yell.ge', 'new', 'medium'),
  ('Peri Nail Bar', 'Nail Salon', 'Vake', '6 I. Kutateladze St.', '(599) 14 22 99', 'yell.ge', 'new', 'medium'),
  ('Lilac Aesthetic Nails', 'Nail Salon', 'Saburtalo', '8 B. Zhgenti St.', '(557) 09 08 05', 'yell.ge', 'new', 'medium'),
  ('Lady Space', 'Nail Salon', 'Chugureti', '117 Agmashenebeli Ave.', '(555) 170 270', 'yell.ge', 'new', 'medium'),
  ('Candy Nails', 'Nail Salon', 'Gldani', '14 Khizanishvili St.', '(511) 23 42 34', 'yell.ge', 'new', 'medium'),
  ('Nail Care Studio', 'Nail Salon', 'Saburtalo', '17 Kazbegi Ave.', '(555) 55 64 62', 'yell.ge', 'new', 'medium'),
  ('Princess Nail & Beauty', 'Nail Salon', 'Saburtalo', '11b Bakhtrioni St.', '(514) 88 82 28', 'yell.ge', 'new', 'medium'),
  ('Nail Beauty Studio', 'Nail Salon', 'Saburtalo', '13 Kazbegi Ave.', '(591) 81 25 25', 'yell.ge', 'new', 'medium'),
  ('Beauty House Nail Art', 'Nail Salon', 'Sololaki', '1 Machabeli St.', '(551) 08 77 80', 'yell.ge', 'new', 'medium'),
  ('Beauty Line Nails', 'Nail Salon', 'Gldani', '30 Khizanishvili St.', '(557) 77 88 45', 'yell.ge', 'new', 'medium'),
  ('Nail Boutique', 'Nail Salon', 'Nadzaladevi', '24 Depo St.', '(595) 99 95 59', 'yell.ge', 'new', 'medium'),
  ('Lux Esthetic Nails', 'Nail Salon', 'Gldani', '53 I. Vekua St.', '(557) 74 93 40', 'yell.ge', 'new', 'medium'),
  ('In Heaven Tbilisi', 'Nail Salon', 'Vera', '23 Melikishvili St.', '(598) 62 51 51', 'yell.ge', 'new', 'medium'),
  ('Nail Sunny', 'Nail Salon', 'Saburtalo', '61 Tsintsadze St.', '(032) 256 04 08', 'yell.ge', 'new', 'medium'),
  ('Aura Nails & Beauty', 'Nail Salon', 'Vake', '5 Mosashvili St.', '(595) 44 33 43', 'yell.ge', 'new', 'medium'),
  ('Glamourama', 'Nail Salon', 'Gldani', '41/43 I. Vekua St.', '(555) 31 71 17', 'yell.ge', 'new', 'medium'),
  ('Nail Masters Club', 'Nail Salon', 'Saburtalo', '3 Mitskevich St.', '(595) 55 88 00', 'yell.ge', 'new', 'medium'),
  ('Pattern Nail Club', 'Nail Salon', 'Saburtalo', '77 Nutsubidze St.', '(591) 444 494', 'yell.ge', 'new', 'medium'),
  ('Tiffany Nail Bar', 'Nail Salon', 'Gldani', '14 I. Vekua St.', '(555) 65 88 99', 'yell.ge', 'new', 'medium');

-- Batch 14: rows 651-700
INSERT INTO leads (name, category, district, address, phone, source, status, priority) VALUES
  ('Laque Nails', 'Nail Salon', 'Vake', '64 Paliashvili St.', '(555) 33 55 93', 'yell.ge', 'new', 'medium'),
  ('Nail Hub', 'Nail Salon', 'Gldani', '43 I. Vekua St.', '(557) 71 00 89', 'yell.ge', 'new', 'medium'),
  ('Khatos Nail Academy', 'Nail Salon', 'Vake', '25 Chavchavadze Ave.', '(555) 64 27 38', 'yell.ge', 'new', 'medium'),
  ('Nail Gardens', 'Nail Salon', 'Saburtalo', '14 Mitskevich St.', '(571) 22 90 22', 'yell.ge', 'new', 'medium'),
  ('Nail Lab', 'Nail Salon', 'Gldani', '4 Vasadze St.', '(595) 06 06 22', 'yell.ge', 'new', 'medium'),
  ('Flower Room', 'Flower Shop', 'Vake', '19 I. Abashidze St.', '(571) 10 42 41', 'yell.ge', 'new', 'medium'),
  ('Songflowers', 'Flower Shop', 'Didi Digomi', '57 Rostevan St.', '(511) 23 88 88', 'yell.ge', 'new', 'medium'),
  ('Lavanderia Flowers', 'Flower Shop', 'Nadzaladevi', '2 Ts. Dadiani St.', '(571) 12 25 29', 'yell.ge', 'new', 'medium'),
  ('Oasis Flowers', 'Flower Shop', 'Saburtalo', '35 Peking St.', '(593) 27 41 33', 'yell.ge', 'new', 'medium'),
  ('Apriori Flowers', 'Flower Shop', 'Gldani', '47 I. Vekua St.', '(593) 57 51 41', 'yell.ge', 'new', 'medium'),
  ('Flower Factory', 'Flower Shop', 'Vera', '1 Petrashvili St.', '(593) 47 47 47', 'yell.ge', 'new', 'medium'),
  ('Freesia Flowers', 'Flower Shop', 'Vake', '2a Paliashvili St.', '(557) 49 52 55', 'yell.ge', 'new', 'medium'),
  ('Flower Garden', 'Flower Shop', 'Saburtalo', '1 University St.', '(595) 90 51 09', 'yell.ge', 'new', 'medium'),
  ('Marta Flowers', 'Flower Shop', 'Gldani', '84 Kerch St.', '(592) 421 421', 'yell.ge', 'new', 'medium'),
  ('Green House Flowers', 'Flower Shop', 'Ortachala', '52 Gorgasali St.', '(599) 04 08 66', 'yell.ge', 'new', 'medium'),
  ('Mao Flowers', 'Flower Shop', 'Saburtalo', '20a Kazbegi Ave.', '283 49 48', 'yell.ge', 'new', 'medium'),
  ('Orientali Flowers', 'Flower Shop', 'Saburtalo', '1 University St.', '(598) 00 30 70', 'yell.ge', 'new', 'medium'),
  ('Plumeria', 'Flower Shop', 'Saburtalo', '2 Ana Kalandadze St.', '(568) 84 06 10', 'yell.ge', 'new', 'medium'),
  ('Sisters Flower Shop', 'Flower Shop', 'Saburtalo', '5 University St.', '(577) 77 93 26', 'yell.ge', 'new', 'medium'),
  ('Papavero Flowers', 'Flower Shop', 'Vera', '47 Barnov St.', '(593) 40 07 09', 'yell.ge', 'new', 'medium'),
  ('La-Flor', 'Flower Shop', 'Temqa', '34 Gia Romelashvili St.', '(579) 34 37 44', 'yell.ge', 'new', 'medium'),
  ('Flowers F-Lovers', 'Flower Shop', 'Vake', '27/29 Paliashvili St.', '(577) 72 18 18', 'yell.ge', 'new', 'medium'),
  ('Gloria Flowers', 'Flower Shop', 'Saburtalo', '14a Shartava St.', '(592) 74 44 04', 'yell.ge', 'new', 'medium'),
  ('Aprili Flowers', 'Flower Shop', 'Vera', '40 Kostava St.', '(571) 00 85 24', 'yell.ge', 'new', 'medium'),
  ('FlorGift', 'Flower Shop', 'Isani', '65a St. Ketevani Ave.', '(593) 23 56 70', 'yell.ge', 'new', 'medium'),
  ('MixTech Xiaomi Service', 'Phone Repair', 'Didube', '12 Tamar Mepe Ave.', '2 500 256', 'yell.ge', 'new', 'medium'),
  ('iCare Georgia', 'Phone Repair', 'Gldani', 'Gldani Mall', '(555) 00 80 03', 'yell.ge', 'new', 'medium'),
  ('Bring & Fix Georgia', 'Phone Repair', 'Didube', '43 Tsereteli Ave.', '(598) 37 78 48', 'yell.ge', 'new', 'medium'),
  ('Mobile Hub', 'Phone Repair', 'Varketili', '1 Khomleli St.', '(511) 12 12 17', 'yell.ge', 'new', 'medium'),
  ('MyMobi', 'Phone Repair', 'Vashlijvari', '15 Godziashvili St.', '(555) 55 67 67', 'yell.ge', 'new', 'medium'),
  ('iFix Georgia', 'Phone Repair', 'Didube', '19 Tsabadze St.', '(557) 74 78 48', 'yell.ge', 'new', 'medium'),
  ('Solo Service', 'Phone Repair', 'Vake', '41 Chavchavadze Ave.', '(558) 40 40 50', 'yell.ge', 'new', 'medium'),
  ('Smartphone Repair', 'Phone Repair', 'Didube', '5a Tevdore Mgvdeli St.', '(557) 00 30 07', 'yell.ge', 'new', 'medium'),
  ('Technoline Mobile Service', 'Phone Repair', 'Saburtalo', '26 Tsintsadze St.', '230 40 80', 'yell.ge', 'new', 'medium'),
  ('iSupport Apple Service', 'Phone Repair', 'Saburtalo', '12 Tsintsadze St.', '230 10 01', 'yell.ge', 'new', 'medium'),
  ('iDoctor', 'Phone Repair', 'Saburtalo', '4 Tsintsadze St.', '(557) 88 88 68', 'yell.ge', 'new', 'medium'),
  ('L Comp Service', 'Computer Repair', 'Varketili', 'Kaloubani St.', '(571) 21 12 90', 'yell.ge', 'new', 'medium'),
  ('ACE Electronics', 'Computer Repair', 'Varketili', 'Kaloubani St.', '(597) 850 850', 'yell.ge', 'new', 'medium'),
  ('GIS Computer', 'Computer Repair', 'Saburtalo', '53 Kavtaradze St.', '(577) 79 97 57', 'yell.ge', 'new', 'medium'),
  ('Computer Service (Agmashenebeli)', 'Computer Repair', 'Chugureti', '193 Agmashenebeli Ave.', '(574) 17 33 99', 'yell.ge', 'new', 'medium'),
  ('Laptop Centre', 'Computer Repair', 'Chugureti', '29 Uznadze St.', '(597) 700 067', 'yell.ge', 'new', 'medium'),
  ('IT Master', 'Computer Repair', 'Didube', '77a Tsereteli Ave.', '(577) 79 76 10', 'yell.ge', 'new', 'medium'),
  ('Fast Compi', 'Computer Repair', 'Nadzaladevi', 'Kartli I turn', '(579) 00 88 86', 'yell.ge', 'new', 'medium'),
  ('ServiceComplect', 'Computer Repair', 'Chugureti', '75 Tsinamdzgvrishvili St.', '(599) 951 953', 'yell.ge', 'new', 'medium'),
  ('Largo Technics Service', 'Computer Repair', 'Saburtalo', '35 Shartava St.', '(579) 22 58 59', 'yell.ge', 'new', 'medium'),
  ('Ultra Service', 'Computer Repair', 'Digomi', '4 N. Bokhua St.', '(577) 04 57 47', 'yell.ge', 'new', 'medium'),
  ('Forea Optics', 'Optical', 'Gldani', '53 I. Vekua St.', '(593) 72 22 66', 'yell.ge', 'new', 'medium'),
  ('New Optics', 'Optical', 'Vake', '17 Levan Mikeladze St.', '(593) 17 15 42', 'yell.ge', 'new', 'medium'),
  ('Tvali Optics', 'Optical', 'Saburtalo', '43a Kazbegi Ave.', '(577) 74 41 44', 'yell.ge', 'new', 'medium'),
  ('Mari+ Optics', 'Optical', 'Didube', '14 Tamar Mepe Ave.', '(558) 640 680', 'yell.ge', 'new', 'medium');

-- Batch 15: rows 701-728
INSERT INTO leads (name, category, district, address, phone, source, status, priority) VALUES
  ('Express Optics', 'Optical', 'Didube', '17 Tamar Mepe Ave.', '(570) 70 10 30', 'yell.ge', 'new', 'medium'),
  ('Aphina Optics', 'Optical', 'Didube', '14/16 Tamar Mepe Ave.', '(571) 72 37 45', 'yell.ge', 'new', 'medium'),
  ('Gallery Glasses', 'Optical', 'Saburtalo', '25 Peking St.', '(598) 19 59 69', 'yell.ge', 'new', 'medium'),
  ('Modi Optics', 'Optical', 'Chugureti', 'Agmashenebeli Alley 213 Tbilisi Mall', '(577) 18 00 18', 'yell.ge', 'new', 'medium'),
  ('Sanqei Optics', 'Optical', 'Didube', '23 Tamar Mepe Ave.', '(599) 26 73 70', 'yell.ge', 'new', 'medium'),
  ('Italoptic', 'Optical', 'Saburtalo', '31a Peking St.', '(593) 94 87 01', 'yell.ge', 'new', 'medium'),
  ('Afflelou Optics', 'Optical', 'Saburtalo', '1 Kavtaradze St. City Mall', '(577) 35 99 50', 'yell.ge', 'new', 'medium'),
  ('Solo Optics', 'Optical', 'Didube', '16 Tamar Mepe Ave.', '(577) 92 63 03', 'yell.ge', 'new', 'medium'),
  ('Ober Optics', 'Optical', 'Saburtalo', '76b Vazha-Pshavela Ave.', '(599) 18 32 62', 'yell.ge', 'new', 'medium'),
  ('Optics N1', 'Optical', 'Gldani', '23 I. Vekua St.', '(599) 73 72 77', 'yell.ge', 'new', 'medium'),
  ('Benissimo Optics', 'Optical', 'Didube', '23 Tamar Mepe Ave.', '(579) 03 88 11', 'yell.ge', 'new', 'medium'),
  ('Fotine Optics', 'Optical', 'Didi Digomi', '4 Petre Iberi St.', '(551) 54 44 47', 'yell.ge', 'new', 'medium'),
  ('Jabadari Optics', 'Optical', 'Didube', '14 Tamar Mepe Ave.', '225 38 78', 'yell.ge', 'new', 'medium'),
  ('Linza Optics', 'Optical', 'Didube', '14 Tamar Mepe Ave.', '(595) 406 506', 'yell.ge', 'new', 'medium'),
  ('Mzera Optics', 'Optical', 'Didube', '18 Tamar Mepe Ave.', '(570) 10 11 79', 'yell.ge', 'new', 'medium'),
  ('Mad Men Barbershop', 'Barber', 'Gldani', '16a I. Vekua St.', '(557) 34 40 00', 'yell.ge', 'new', 'medium'),
  ('Chop-Chop Men''s Haircuts', 'Barber', 'Saburtalo', '1 Kazbegi Ave.', '(597) 71 11 44', 'yell.ge', 'new', 'medium'),
  ('A''Meus Man', 'Barber', 'Vake', '63 Paliashvili St.', '(551) 47 22 22', 'yell.ge', 'new', 'medium'),
  ('Barber King', 'Barber', 'Saburtalo', '7 Chabukiani St.', '(593) 180 184', 'yell.ge', 'new', 'medium'),
  ('Garrison Barbershop', 'Barber', 'Vake', '62 I. Abashidze St.', '(555) 62 09 62', 'yell.ge', 'new', 'medium'),
  ('Camora Barber', 'Barber', 'Mtatsminda', '23 Rustaveli Ave.', '(555) 12 22 79', 'yell.ge', 'new', 'medium'),
  ('Brothers Barbershop', 'Barber', 'Vake', '5 Kavsadze St.', '(557) 33 30 68', 'yell.ge', 'new', 'medium'),
  ('Arsenal Barber Shop', 'Barber', 'Avlabari', '5 Bochorma St.', '(511) 20 20 80', 'yell.ge', 'new', 'medium'),
  ('Mafia Barbershop', 'Barber', 'Chugureti', '23 Agmashenebeli Ave.', '(555) 23 23 70', 'yell.ge', 'new', 'medium'),
  ('Groove District Barber', 'Barber', 'Saburtalo', '3 Politkovskaya St. b. 30', '(593) 28 67 19', 'yell.ge', 'new', 'medium'),
  ('4 Sharp Barber', 'Barber', 'Didi Digomi', '32a G. Brtskinvale St.', '500 508 707', 'yell.ge', 'new', 'medium'),
  ('Chop Garage Barbershop', 'Barber', 'Didi Digomi', '7 Mirian Mepe St.', '(555) 41 31 77', 'yell.ge', 'new', 'medium'),
  ('The Barber Shop Men''s', 'Barber', 'Vake', '42 I. Abashidze St.', '(555) 40 10 42', 'yell.ge', 'new', 'medium');
